/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_dynamics_linearization_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s2[459] = {24, 24, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 168, 192, 216, 240, 264, 288, 312, 336, 360, 384, 408, 432, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s3[303] = {24, 12, 0, 24, 48, 72, 96, 120, 144, 168, 192, 216, 240, 264, 288, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};
static const casadi_int casadi_s4[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};

/* g_linearization_A:(q[12],v[12],u[12],iH[12x12])->(A[24x24,432nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a0;
  if (res[0]!=0) res[0][68]=a0;
  if (res[0]!=0) res[0][69]=a0;
  if (res[0]!=0) res[0][70]=a0;
  if (res[0]!=0) res[0][71]=a0;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  if (res[0]!=0) res[0][76]=a0;
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a0;
  if (res[0]!=0) res[0][81]=a0;
  if (res[0]!=0) res[0][82]=a0;
  if (res[0]!=0) res[0][83]=a0;
  if (res[0]!=0) res[0][84]=a0;
  if (res[0]!=0) res[0][85]=a0;
  if (res[0]!=0) res[0][86]=a0;
  if (res[0]!=0) res[0][87]=a0;
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a0;
  if (res[0]!=0) res[0][90]=a0;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a0;
  if (res[0]!=0) res[0][93]=a0;
  if (res[0]!=0) res[0][94]=a0;
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a0;
  if (res[0]!=0) res[0][97]=a0;
  if (res[0]!=0) res[0][98]=a0;
  if (res[0]!=0) res[0][99]=a0;
  if (res[0]!=0) res[0][100]=a0;
  if (res[0]!=0) res[0][101]=a0;
  if (res[0]!=0) res[0][102]=a0;
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a0;
  if (res[0]!=0) res[0][107]=a0;
  if (res[0]!=0) res[0][108]=a0;
  if (res[0]!=0) res[0][109]=a0;
  if (res[0]!=0) res[0][110]=a0;
  if (res[0]!=0) res[0][111]=a0;
  if (res[0]!=0) res[0][112]=a0;
  if (res[0]!=0) res[0][113]=a0;
  if (res[0]!=0) res[0][114]=a0;
  if (res[0]!=0) res[0][115]=a0;
  if (res[0]!=0) res[0][116]=a0;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a0;
  if (res[0]!=0) res[0][119]=a0;
  if (res[0]!=0) res[0][120]=a0;
  if (res[0]!=0) res[0][121]=a0;
  if (res[0]!=0) res[0][122]=a0;
  if (res[0]!=0) res[0][123]=a0;
  if (res[0]!=0) res[0][124]=a0;
  if (res[0]!=0) res[0][125]=a0;
  if (res[0]!=0) res[0][126]=a0;
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a0;
  if (res[0]!=0) res[0][129]=a0;
  if (res[0]!=0) res[0][130]=a0;
  if (res[0]!=0) res[0][131]=a0;
  if (res[0]!=0) res[0][132]=a0;
  if (res[0]!=0) res[0][133]=a0;
  if (res[0]!=0) res[0][134]=a0;
  if (res[0]!=0) res[0][135]=a0;
  if (res[0]!=0) res[0][136]=a0;
  if (res[0]!=0) res[0][137]=a0;
  if (res[0]!=0) res[0][138]=a0;
  if (res[0]!=0) res[0][139]=a0;
  if (res[0]!=0) res[0][140]=a0;
  if (res[0]!=0) res[0][141]=a0;
  if (res[0]!=0) res[0][142]=a0;
  if (res[0]!=0) res[0][143]=a0;
  a1=1.;
  if (res[0]!=0) res[0][144]=a1;
  if (res[0]!=0) res[0][145]=a0;
  if (res[0]!=0) res[0][146]=a0;
  if (res[0]!=0) res[0][147]=a0;
  if (res[0]!=0) res[0][148]=a0;
  if (res[0]!=0) res[0][149]=a0;
  if (res[0]!=0) res[0][150]=a0;
  if (res[0]!=0) res[0][151]=a0;
  if (res[0]!=0) res[0][152]=a0;
  if (res[0]!=0) res[0][153]=a0;
  if (res[0]!=0) res[0][154]=a0;
  if (res[0]!=0) res[0][155]=a0;
  a2=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][156]=a2;
  a2=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][157]=a2;
  a2=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][158]=a2;
  a2=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][159]=a2;
  a2=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][160]=a2;
  a2=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][161]=a2;
  a2=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][162]=a2;
  a2=arg[3]? arg[3][7] : 0;
  if (res[0]!=0) res[0][163]=a2;
  a2=arg[3]? arg[3][8] : 0;
  if (res[0]!=0) res[0][164]=a2;
  a2=arg[3]? arg[3][9] : 0;
  if (res[0]!=0) res[0][165]=a2;
  a2=arg[3]? arg[3][10] : 0;
  if (res[0]!=0) res[0][166]=a2;
  a2=arg[3]? arg[3][11] : 0;
  if (res[0]!=0) res[0][167]=a2;
  if (res[0]!=0) res[0][168]=a0;
  if (res[0]!=0) res[0][169]=a1;
  if (res[0]!=0) res[0][170]=a0;
  if (res[0]!=0) res[0][171]=a0;
  if (res[0]!=0) res[0][172]=a0;
  if (res[0]!=0) res[0][173]=a0;
  if (res[0]!=0) res[0][174]=a0;
  if (res[0]!=0) res[0][175]=a0;
  if (res[0]!=0) res[0][176]=a0;
  if (res[0]!=0) res[0][177]=a0;
  if (res[0]!=0) res[0][178]=a0;
  if (res[0]!=0) res[0][179]=a0;
  a2=arg[3]? arg[3][12] : 0;
  if (res[0]!=0) res[0][180]=a2;
  a2=arg[3]? arg[3][13] : 0;
  if (res[0]!=0) res[0][181]=a2;
  a2=arg[3]? arg[3][14] : 0;
  if (res[0]!=0) res[0][182]=a2;
  a2=arg[3]? arg[3][15] : 0;
  if (res[0]!=0) res[0][183]=a2;
  a2=arg[3]? arg[3][16] : 0;
  if (res[0]!=0) res[0][184]=a2;
  a2=arg[3]? arg[3][17] : 0;
  if (res[0]!=0) res[0][185]=a2;
  a2=arg[3]? arg[3][18] : 0;
  if (res[0]!=0) res[0][186]=a2;
  a2=arg[3]? arg[3][19] : 0;
  if (res[0]!=0) res[0][187]=a2;
  a2=arg[3]? arg[3][20] : 0;
  if (res[0]!=0) res[0][188]=a2;
  a2=arg[3]? arg[3][21] : 0;
  if (res[0]!=0) res[0][189]=a2;
  a2=arg[3]? arg[3][22] : 0;
  if (res[0]!=0) res[0][190]=a2;
  a2=arg[3]? arg[3][23] : 0;
  if (res[0]!=0) res[0][191]=a2;
  if (res[0]!=0) res[0][192]=a0;
  if (res[0]!=0) res[0][193]=a0;
  if (res[0]!=0) res[0][194]=a1;
  if (res[0]!=0) res[0][195]=a0;
  if (res[0]!=0) res[0][196]=a0;
  if (res[0]!=0) res[0][197]=a0;
  if (res[0]!=0) res[0][198]=a0;
  if (res[0]!=0) res[0][199]=a0;
  if (res[0]!=0) res[0][200]=a0;
  if (res[0]!=0) res[0][201]=a0;
  if (res[0]!=0) res[0][202]=a0;
  if (res[0]!=0) res[0][203]=a0;
  a2=arg[3]? arg[3][24] : 0;
  if (res[0]!=0) res[0][204]=a2;
  a2=arg[3]? arg[3][25] : 0;
  if (res[0]!=0) res[0][205]=a2;
  a2=arg[3]? arg[3][26] : 0;
  if (res[0]!=0) res[0][206]=a2;
  a2=arg[3]? arg[3][27] : 0;
  if (res[0]!=0) res[0][207]=a2;
  a2=arg[3]? arg[3][28] : 0;
  if (res[0]!=0) res[0][208]=a2;
  a2=arg[3]? arg[3][29] : 0;
  if (res[0]!=0) res[0][209]=a2;
  a2=arg[3]? arg[3][30] : 0;
  if (res[0]!=0) res[0][210]=a2;
  a2=arg[3]? arg[3][31] : 0;
  if (res[0]!=0) res[0][211]=a2;
  a2=arg[3]? arg[3][32] : 0;
  if (res[0]!=0) res[0][212]=a2;
  a2=arg[3]? arg[3][33] : 0;
  if (res[0]!=0) res[0][213]=a2;
  a2=arg[3]? arg[3][34] : 0;
  if (res[0]!=0) res[0][214]=a2;
  a2=arg[3]? arg[3][35] : 0;
  if (res[0]!=0) res[0][215]=a2;
  if (res[0]!=0) res[0][216]=a0;
  if (res[0]!=0) res[0][217]=a0;
  if (res[0]!=0) res[0][218]=a0;
  if (res[0]!=0) res[0][219]=a1;
  if (res[0]!=0) res[0][220]=a0;
  if (res[0]!=0) res[0][221]=a0;
  if (res[0]!=0) res[0][222]=a0;
  if (res[0]!=0) res[0][223]=a0;
  if (res[0]!=0) res[0][224]=a0;
  if (res[0]!=0) res[0][225]=a0;
  if (res[0]!=0) res[0][226]=a0;
  if (res[0]!=0) res[0][227]=a0;
  a2=arg[3]? arg[3][36] : 0;
  if (res[0]!=0) res[0][228]=a2;
  a2=arg[3]? arg[3][37] : 0;
  if (res[0]!=0) res[0][229]=a2;
  a2=arg[3]? arg[3][38] : 0;
  if (res[0]!=0) res[0][230]=a2;
  a2=arg[3]? arg[3][39] : 0;
  if (res[0]!=0) res[0][231]=a2;
  a2=arg[3]? arg[3][40] : 0;
  if (res[0]!=0) res[0][232]=a2;
  a2=arg[3]? arg[3][41] : 0;
  if (res[0]!=0) res[0][233]=a2;
  a2=arg[3]? arg[3][42] : 0;
  if (res[0]!=0) res[0][234]=a2;
  a2=arg[3]? arg[3][43] : 0;
  if (res[0]!=0) res[0][235]=a2;
  a2=arg[3]? arg[3][44] : 0;
  if (res[0]!=0) res[0][236]=a2;
  a2=arg[3]? arg[3][45] : 0;
  if (res[0]!=0) res[0][237]=a2;
  a2=arg[3]? arg[3][46] : 0;
  if (res[0]!=0) res[0][238]=a2;
  a2=arg[3]? arg[3][47] : 0;
  if (res[0]!=0) res[0][239]=a2;
  if (res[0]!=0) res[0][240]=a0;
  if (res[0]!=0) res[0][241]=a0;
  if (res[0]!=0) res[0][242]=a0;
  if (res[0]!=0) res[0][243]=a0;
  if (res[0]!=0) res[0][244]=a1;
  if (res[0]!=0) res[0][245]=a0;
  if (res[0]!=0) res[0][246]=a0;
  if (res[0]!=0) res[0][247]=a0;
  if (res[0]!=0) res[0][248]=a0;
  if (res[0]!=0) res[0][249]=a0;
  if (res[0]!=0) res[0][250]=a0;
  if (res[0]!=0) res[0][251]=a0;
  a2=arg[3]? arg[3][48] : 0;
  if (res[0]!=0) res[0][252]=a2;
  a2=arg[3]? arg[3][49] : 0;
  if (res[0]!=0) res[0][253]=a2;
  a2=arg[3]? arg[3][50] : 0;
  if (res[0]!=0) res[0][254]=a2;
  a2=arg[3]? arg[3][51] : 0;
  if (res[0]!=0) res[0][255]=a2;
  a2=arg[3]? arg[3][52] : 0;
  if (res[0]!=0) res[0][256]=a2;
  a2=arg[3]? arg[3][53] : 0;
  if (res[0]!=0) res[0][257]=a2;
  a2=arg[3]? arg[3][54] : 0;
  if (res[0]!=0) res[0][258]=a2;
  a2=arg[3]? arg[3][55] : 0;
  if (res[0]!=0) res[0][259]=a2;
  a2=arg[3]? arg[3][56] : 0;
  if (res[0]!=0) res[0][260]=a2;
  a2=arg[3]? arg[3][57] : 0;
  if (res[0]!=0) res[0][261]=a2;
  a2=arg[3]? arg[3][58] : 0;
  if (res[0]!=0) res[0][262]=a2;
  a2=arg[3]? arg[3][59] : 0;
  if (res[0]!=0) res[0][263]=a2;
  if (res[0]!=0) res[0][264]=a0;
  if (res[0]!=0) res[0][265]=a0;
  if (res[0]!=0) res[0][266]=a0;
  if (res[0]!=0) res[0][267]=a0;
  if (res[0]!=0) res[0][268]=a0;
  if (res[0]!=0) res[0][269]=a1;
  if (res[0]!=0) res[0][270]=a0;
  if (res[0]!=0) res[0][271]=a0;
  if (res[0]!=0) res[0][272]=a0;
  if (res[0]!=0) res[0][273]=a0;
  if (res[0]!=0) res[0][274]=a0;
  if (res[0]!=0) res[0][275]=a0;
  a2=arg[3]? arg[3][60] : 0;
  if (res[0]!=0) res[0][276]=a2;
  a2=arg[3]? arg[3][61] : 0;
  if (res[0]!=0) res[0][277]=a2;
  a2=arg[3]? arg[3][62] : 0;
  if (res[0]!=0) res[0][278]=a2;
  a2=arg[3]? arg[3][63] : 0;
  if (res[0]!=0) res[0][279]=a2;
  a2=arg[3]? arg[3][64] : 0;
  if (res[0]!=0) res[0][280]=a2;
  a2=arg[3]? arg[3][65] : 0;
  if (res[0]!=0) res[0][281]=a2;
  a2=arg[3]? arg[3][66] : 0;
  if (res[0]!=0) res[0][282]=a2;
  a2=arg[3]? arg[3][67] : 0;
  if (res[0]!=0) res[0][283]=a2;
  a2=arg[3]? arg[3][68] : 0;
  if (res[0]!=0) res[0][284]=a2;
  a2=arg[3]? arg[3][69] : 0;
  if (res[0]!=0) res[0][285]=a2;
  a2=arg[3]? arg[3][70] : 0;
  if (res[0]!=0) res[0][286]=a2;
  a2=arg[3]? arg[3][71] : 0;
  if (res[0]!=0) res[0][287]=a2;
  if (res[0]!=0) res[0][288]=a0;
  if (res[0]!=0) res[0][289]=a0;
  if (res[0]!=0) res[0][290]=a0;
  if (res[0]!=0) res[0][291]=a0;
  if (res[0]!=0) res[0][292]=a0;
  if (res[0]!=0) res[0][293]=a0;
  if (res[0]!=0) res[0][294]=a1;
  if (res[0]!=0) res[0][295]=a0;
  if (res[0]!=0) res[0][296]=a0;
  if (res[0]!=0) res[0][297]=a0;
  if (res[0]!=0) res[0][298]=a0;
  if (res[0]!=0) res[0][299]=a0;
  a2=arg[3]? arg[3][72] : 0;
  if (res[0]!=0) res[0][300]=a2;
  a2=arg[3]? arg[3][73] : 0;
  if (res[0]!=0) res[0][301]=a2;
  a2=arg[3]? arg[3][74] : 0;
  if (res[0]!=0) res[0][302]=a2;
  a2=arg[3]? arg[3][75] : 0;
  if (res[0]!=0) res[0][303]=a2;
  a2=arg[3]? arg[3][76] : 0;
  if (res[0]!=0) res[0][304]=a2;
  a2=arg[3]? arg[3][77] : 0;
  if (res[0]!=0) res[0][305]=a2;
  a2=arg[3]? arg[3][78] : 0;
  if (res[0]!=0) res[0][306]=a2;
  a2=arg[3]? arg[3][79] : 0;
  if (res[0]!=0) res[0][307]=a2;
  a2=arg[3]? arg[3][80] : 0;
  if (res[0]!=0) res[0][308]=a2;
  a2=arg[3]? arg[3][81] : 0;
  if (res[0]!=0) res[0][309]=a2;
  a2=arg[3]? arg[3][82] : 0;
  if (res[0]!=0) res[0][310]=a2;
  a2=arg[3]? arg[3][83] : 0;
  if (res[0]!=0) res[0][311]=a2;
  if (res[0]!=0) res[0][312]=a0;
  if (res[0]!=0) res[0][313]=a0;
  if (res[0]!=0) res[0][314]=a0;
  if (res[0]!=0) res[0][315]=a0;
  if (res[0]!=0) res[0][316]=a0;
  if (res[0]!=0) res[0][317]=a0;
  if (res[0]!=0) res[0][318]=a0;
  if (res[0]!=0) res[0][319]=a1;
  if (res[0]!=0) res[0][320]=a0;
  if (res[0]!=0) res[0][321]=a0;
  if (res[0]!=0) res[0][322]=a0;
  if (res[0]!=0) res[0][323]=a0;
  a2=arg[3]? arg[3][84] : 0;
  if (res[0]!=0) res[0][324]=a2;
  a2=arg[3]? arg[3][85] : 0;
  if (res[0]!=0) res[0][325]=a2;
  a2=arg[3]? arg[3][86] : 0;
  if (res[0]!=0) res[0][326]=a2;
  a2=arg[3]? arg[3][87] : 0;
  if (res[0]!=0) res[0][327]=a2;
  a2=arg[3]? arg[3][88] : 0;
  if (res[0]!=0) res[0][328]=a2;
  a2=arg[3]? arg[3][89] : 0;
  if (res[0]!=0) res[0][329]=a2;
  a2=arg[3]? arg[3][90] : 0;
  if (res[0]!=0) res[0][330]=a2;
  a2=arg[3]? arg[3][91] : 0;
  if (res[0]!=0) res[0][331]=a2;
  a2=arg[3]? arg[3][92] : 0;
  if (res[0]!=0) res[0][332]=a2;
  a2=arg[3]? arg[3][93] : 0;
  if (res[0]!=0) res[0][333]=a2;
  a2=arg[3]? arg[3][94] : 0;
  if (res[0]!=0) res[0][334]=a2;
  a2=arg[3]? arg[3][95] : 0;
  if (res[0]!=0) res[0][335]=a2;
  if (res[0]!=0) res[0][336]=a0;
  if (res[0]!=0) res[0][337]=a0;
  if (res[0]!=0) res[0][338]=a0;
  if (res[0]!=0) res[0][339]=a0;
  if (res[0]!=0) res[0][340]=a0;
  if (res[0]!=0) res[0][341]=a0;
  if (res[0]!=0) res[0][342]=a0;
  if (res[0]!=0) res[0][343]=a0;
  if (res[0]!=0) res[0][344]=a1;
  if (res[0]!=0) res[0][345]=a0;
  if (res[0]!=0) res[0][346]=a0;
  if (res[0]!=0) res[0][347]=a0;
  a2=arg[3]? arg[3][96] : 0;
  if (res[0]!=0) res[0][348]=a2;
  a2=arg[3]? arg[3][97] : 0;
  if (res[0]!=0) res[0][349]=a2;
  a2=arg[3]? arg[3][98] : 0;
  if (res[0]!=0) res[0][350]=a2;
  a2=arg[3]? arg[3][99] : 0;
  if (res[0]!=0) res[0][351]=a2;
  a2=arg[3]? arg[3][100] : 0;
  if (res[0]!=0) res[0][352]=a2;
  a2=arg[3]? arg[3][101] : 0;
  if (res[0]!=0) res[0][353]=a2;
  a2=arg[3]? arg[3][102] : 0;
  if (res[0]!=0) res[0][354]=a2;
  a2=arg[3]? arg[3][103] : 0;
  if (res[0]!=0) res[0][355]=a2;
  a2=arg[3]? arg[3][104] : 0;
  if (res[0]!=0) res[0][356]=a2;
  a2=arg[3]? arg[3][105] : 0;
  if (res[0]!=0) res[0][357]=a2;
  a2=arg[3]? arg[3][106] : 0;
  if (res[0]!=0) res[0][358]=a2;
  a2=arg[3]? arg[3][107] : 0;
  if (res[0]!=0) res[0][359]=a2;
  if (res[0]!=0) res[0][360]=a0;
  if (res[0]!=0) res[0][361]=a0;
  if (res[0]!=0) res[0][362]=a0;
  if (res[0]!=0) res[0][363]=a0;
  if (res[0]!=0) res[0][364]=a0;
  if (res[0]!=0) res[0][365]=a0;
  if (res[0]!=0) res[0][366]=a0;
  if (res[0]!=0) res[0][367]=a0;
  if (res[0]!=0) res[0][368]=a0;
  if (res[0]!=0) res[0][369]=a1;
  if (res[0]!=0) res[0][370]=a0;
  if (res[0]!=0) res[0][371]=a0;
  a2=arg[3]? arg[3][108] : 0;
  if (res[0]!=0) res[0][372]=a2;
  a2=arg[3]? arg[3][109] : 0;
  if (res[0]!=0) res[0][373]=a2;
  a2=arg[3]? arg[3][110] : 0;
  if (res[0]!=0) res[0][374]=a2;
  a2=arg[3]? arg[3][111] : 0;
  if (res[0]!=0) res[0][375]=a2;
  a2=arg[3]? arg[3][112] : 0;
  if (res[0]!=0) res[0][376]=a2;
  a2=arg[3]? arg[3][113] : 0;
  if (res[0]!=0) res[0][377]=a2;
  a2=arg[3]? arg[3][114] : 0;
  if (res[0]!=0) res[0][378]=a2;
  a2=arg[3]? arg[3][115] : 0;
  if (res[0]!=0) res[0][379]=a2;
  a2=arg[3]? arg[3][116] : 0;
  if (res[0]!=0) res[0][380]=a2;
  a2=arg[3]? arg[3][117] : 0;
  if (res[0]!=0) res[0][381]=a2;
  a2=arg[3]? arg[3][118] : 0;
  if (res[0]!=0) res[0][382]=a2;
  a2=arg[3]? arg[3][119] : 0;
  if (res[0]!=0) res[0][383]=a2;
  if (res[0]!=0) res[0][384]=a0;
  if (res[0]!=0) res[0][385]=a0;
  if (res[0]!=0) res[0][386]=a0;
  if (res[0]!=0) res[0][387]=a0;
  if (res[0]!=0) res[0][388]=a0;
  if (res[0]!=0) res[0][389]=a0;
  if (res[0]!=0) res[0][390]=a0;
  if (res[0]!=0) res[0][391]=a0;
  if (res[0]!=0) res[0][392]=a0;
  if (res[0]!=0) res[0][393]=a0;
  if (res[0]!=0) res[0][394]=a1;
  if (res[0]!=0) res[0][395]=a0;
  a2=arg[3]? arg[3][120] : 0;
  if (res[0]!=0) res[0][396]=a2;
  a2=arg[3]? arg[3][121] : 0;
  if (res[0]!=0) res[0][397]=a2;
  a2=arg[3]? arg[3][122] : 0;
  if (res[0]!=0) res[0][398]=a2;
  a2=arg[3]? arg[3][123] : 0;
  if (res[0]!=0) res[0][399]=a2;
  a2=arg[3]? arg[3][124] : 0;
  if (res[0]!=0) res[0][400]=a2;
  a2=arg[3]? arg[3][125] : 0;
  if (res[0]!=0) res[0][401]=a2;
  a2=arg[3]? arg[3][126] : 0;
  if (res[0]!=0) res[0][402]=a2;
  a2=arg[3]? arg[3][127] : 0;
  if (res[0]!=0) res[0][403]=a2;
  a2=arg[3]? arg[3][128] : 0;
  if (res[0]!=0) res[0][404]=a2;
  a2=arg[3]? arg[3][129] : 0;
  if (res[0]!=0) res[0][405]=a2;
  a2=arg[3]? arg[3][130] : 0;
  if (res[0]!=0) res[0][406]=a2;
  a2=arg[3]? arg[3][131] : 0;
  if (res[0]!=0) res[0][407]=a2;
  if (res[0]!=0) res[0][408]=a0;
  if (res[0]!=0) res[0][409]=a0;
  if (res[0]!=0) res[0][410]=a0;
  if (res[0]!=0) res[0][411]=a0;
  if (res[0]!=0) res[0][412]=a0;
  if (res[0]!=0) res[0][413]=a0;
  if (res[0]!=0) res[0][414]=a0;
  if (res[0]!=0) res[0][415]=a0;
  if (res[0]!=0) res[0][416]=a0;
  if (res[0]!=0) res[0][417]=a0;
  if (res[0]!=0) res[0][418]=a0;
  if (res[0]!=0) res[0][419]=a1;
  a1=arg[3]? arg[3][132] : 0;
  if (res[0]!=0) res[0][420]=a1;
  a1=arg[3]? arg[3][133] : 0;
  if (res[0]!=0) res[0][421]=a1;
  a1=arg[3]? arg[3][134] : 0;
  if (res[0]!=0) res[0][422]=a1;
  a1=arg[3]? arg[3][135] : 0;
  if (res[0]!=0) res[0][423]=a1;
  a1=arg[3]? arg[3][136] : 0;
  if (res[0]!=0) res[0][424]=a1;
  a1=arg[3]? arg[3][137] : 0;
  if (res[0]!=0) res[0][425]=a1;
  a1=arg[3]? arg[3][138] : 0;
  if (res[0]!=0) res[0][426]=a1;
  a1=arg[3]? arg[3][139] : 0;
  if (res[0]!=0) res[0][427]=a1;
  a1=arg[3]? arg[3][140] : 0;
  if (res[0]!=0) res[0][428]=a1;
  a1=arg[3]? arg[3][141] : 0;
  if (res[0]!=0) res[0][429]=a1;
  a1=arg[3]? arg[3][142] : 0;
  if (res[0]!=0) res[0][430]=a1;
  a1=arg[3]? arg[3][143] : 0;
  if (res[0]!=0) res[0][431]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_A(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_A_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_A_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_A_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_A_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_A_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_A_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_A_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_A_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_A_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_A_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_A_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "u";
    case 3: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_A_name_out(casadi_int i){
  switch (i) {
    case 0: return "A";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_A_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_A_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_A_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_linearization_B:(q[12],v[12],iH[12x12])->(B[24x12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  a1=arg[2]? arg[2][0] : 0;
  if (res[0]!=0) res[0][12]=a1;
  a1=arg[2]? arg[2][1] : 0;
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[2]? arg[2][2] : 0;
  if (res[0]!=0) res[0][14]=a1;
  a1=arg[2]? arg[2][3] : 0;
  if (res[0]!=0) res[0][15]=a1;
  a1=arg[2]? arg[2][4] : 0;
  if (res[0]!=0) res[0][16]=a1;
  a1=arg[2]? arg[2][5] : 0;
  if (res[0]!=0) res[0][17]=a1;
  a1=arg[2]? arg[2][6] : 0;
  if (res[0]!=0) res[0][18]=a1;
  a1=arg[2]? arg[2][7] : 0;
  if (res[0]!=0) res[0][19]=a1;
  a1=arg[2]? arg[2][8] : 0;
  if (res[0]!=0) res[0][20]=a1;
  a1=arg[2]? arg[2][9] : 0;
  if (res[0]!=0) res[0][21]=a1;
  a1=arg[2]? arg[2][10] : 0;
  if (res[0]!=0) res[0][22]=a1;
  a1=arg[2]? arg[2][11] : 0;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  a1=arg[2]? arg[2][12] : 0;
  if (res[0]!=0) res[0][36]=a1;
  a1=arg[2]? arg[2][13] : 0;
  if (res[0]!=0) res[0][37]=a1;
  a1=arg[2]? arg[2][14] : 0;
  if (res[0]!=0) res[0][38]=a1;
  a1=arg[2]? arg[2][15] : 0;
  if (res[0]!=0) res[0][39]=a1;
  a1=arg[2]? arg[2][16] : 0;
  if (res[0]!=0) res[0][40]=a1;
  a1=arg[2]? arg[2][17] : 0;
  if (res[0]!=0) res[0][41]=a1;
  a1=arg[2]? arg[2][18] : 0;
  if (res[0]!=0) res[0][42]=a1;
  a1=arg[2]? arg[2][19] : 0;
  if (res[0]!=0) res[0][43]=a1;
  a1=arg[2]? arg[2][20] : 0;
  if (res[0]!=0) res[0][44]=a1;
  a1=arg[2]? arg[2][21] : 0;
  if (res[0]!=0) res[0][45]=a1;
  a1=arg[2]? arg[2][22] : 0;
  if (res[0]!=0) res[0][46]=a1;
  a1=arg[2]? arg[2][23] : 0;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  a1=arg[2]? arg[2][24] : 0;
  if (res[0]!=0) res[0][60]=a1;
  a1=arg[2]? arg[2][25] : 0;
  if (res[0]!=0) res[0][61]=a1;
  a1=arg[2]? arg[2][26] : 0;
  if (res[0]!=0) res[0][62]=a1;
  a1=arg[2]? arg[2][27] : 0;
  if (res[0]!=0) res[0][63]=a1;
  a1=arg[2]? arg[2][28] : 0;
  if (res[0]!=0) res[0][64]=a1;
  a1=arg[2]? arg[2][29] : 0;
  if (res[0]!=0) res[0][65]=a1;
  a1=arg[2]? arg[2][30] : 0;
  if (res[0]!=0) res[0][66]=a1;
  a1=arg[2]? arg[2][31] : 0;
  if (res[0]!=0) res[0][67]=a1;
  a1=arg[2]? arg[2][32] : 0;
  if (res[0]!=0) res[0][68]=a1;
  a1=arg[2]? arg[2][33] : 0;
  if (res[0]!=0) res[0][69]=a1;
  a1=arg[2]? arg[2][34] : 0;
  if (res[0]!=0) res[0][70]=a1;
  a1=arg[2]? arg[2][35] : 0;
  if (res[0]!=0) res[0][71]=a1;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  if (res[0]!=0) res[0][76]=a0;
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a0;
  if (res[0]!=0) res[0][81]=a0;
  if (res[0]!=0) res[0][82]=a0;
  if (res[0]!=0) res[0][83]=a0;
  a1=arg[2]? arg[2][36] : 0;
  if (res[0]!=0) res[0][84]=a1;
  a1=arg[2]? arg[2][37] : 0;
  if (res[0]!=0) res[0][85]=a1;
  a1=arg[2]? arg[2][38] : 0;
  if (res[0]!=0) res[0][86]=a1;
  a1=arg[2]? arg[2][39] : 0;
  if (res[0]!=0) res[0][87]=a1;
  a1=arg[2]? arg[2][40] : 0;
  if (res[0]!=0) res[0][88]=a1;
  a1=arg[2]? arg[2][41] : 0;
  if (res[0]!=0) res[0][89]=a1;
  a1=arg[2]? arg[2][42] : 0;
  if (res[0]!=0) res[0][90]=a1;
  a1=arg[2]? arg[2][43] : 0;
  if (res[0]!=0) res[0][91]=a1;
  a1=arg[2]? arg[2][44] : 0;
  if (res[0]!=0) res[0][92]=a1;
  a1=arg[2]? arg[2][45] : 0;
  if (res[0]!=0) res[0][93]=a1;
  a1=arg[2]? arg[2][46] : 0;
  if (res[0]!=0) res[0][94]=a1;
  a1=arg[2]? arg[2][47] : 0;
  if (res[0]!=0) res[0][95]=a1;
  if (res[0]!=0) res[0][96]=a0;
  if (res[0]!=0) res[0][97]=a0;
  if (res[0]!=0) res[0][98]=a0;
  if (res[0]!=0) res[0][99]=a0;
  if (res[0]!=0) res[0][100]=a0;
  if (res[0]!=0) res[0][101]=a0;
  if (res[0]!=0) res[0][102]=a0;
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a0;
  if (res[0]!=0) res[0][107]=a0;
  a1=arg[2]? arg[2][48] : 0;
  if (res[0]!=0) res[0][108]=a1;
  a1=arg[2]? arg[2][49] : 0;
  if (res[0]!=0) res[0][109]=a1;
  a1=arg[2]? arg[2][50] : 0;
  if (res[0]!=0) res[0][110]=a1;
  a1=arg[2]? arg[2][51] : 0;
  if (res[0]!=0) res[0][111]=a1;
  a1=arg[2]? arg[2][52] : 0;
  if (res[0]!=0) res[0][112]=a1;
  a1=arg[2]? arg[2][53] : 0;
  if (res[0]!=0) res[0][113]=a1;
  a1=arg[2]? arg[2][54] : 0;
  if (res[0]!=0) res[0][114]=a1;
  a1=arg[2]? arg[2][55] : 0;
  if (res[0]!=0) res[0][115]=a1;
  a1=arg[2]? arg[2][56] : 0;
  if (res[0]!=0) res[0][116]=a1;
  a1=arg[2]? arg[2][57] : 0;
  if (res[0]!=0) res[0][117]=a1;
  a1=arg[2]? arg[2][58] : 0;
  if (res[0]!=0) res[0][118]=a1;
  a1=arg[2]? arg[2][59] : 0;
  if (res[0]!=0) res[0][119]=a1;
  if (res[0]!=0) res[0][120]=a0;
  if (res[0]!=0) res[0][121]=a0;
  if (res[0]!=0) res[0][122]=a0;
  if (res[0]!=0) res[0][123]=a0;
  if (res[0]!=0) res[0][124]=a0;
  if (res[0]!=0) res[0][125]=a0;
  if (res[0]!=0) res[0][126]=a0;
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a0;
  if (res[0]!=0) res[0][129]=a0;
  if (res[0]!=0) res[0][130]=a0;
  if (res[0]!=0) res[0][131]=a0;
  a1=arg[2]? arg[2][60] : 0;
  if (res[0]!=0) res[0][132]=a1;
  a1=arg[2]? arg[2][61] : 0;
  if (res[0]!=0) res[0][133]=a1;
  a1=arg[2]? arg[2][62] : 0;
  if (res[0]!=0) res[0][134]=a1;
  a1=arg[2]? arg[2][63] : 0;
  if (res[0]!=0) res[0][135]=a1;
  a1=arg[2]? arg[2][64] : 0;
  if (res[0]!=0) res[0][136]=a1;
  a1=arg[2]? arg[2][65] : 0;
  if (res[0]!=0) res[0][137]=a1;
  a1=arg[2]? arg[2][66] : 0;
  if (res[0]!=0) res[0][138]=a1;
  a1=arg[2]? arg[2][67] : 0;
  if (res[0]!=0) res[0][139]=a1;
  a1=arg[2]? arg[2][68] : 0;
  if (res[0]!=0) res[0][140]=a1;
  a1=arg[2]? arg[2][69] : 0;
  if (res[0]!=0) res[0][141]=a1;
  a1=arg[2]? arg[2][70] : 0;
  if (res[0]!=0) res[0][142]=a1;
  a1=arg[2]? arg[2][71] : 0;
  if (res[0]!=0) res[0][143]=a1;
  if (res[0]!=0) res[0][144]=a0;
  if (res[0]!=0) res[0][145]=a0;
  if (res[0]!=0) res[0][146]=a0;
  if (res[0]!=0) res[0][147]=a0;
  if (res[0]!=0) res[0][148]=a0;
  if (res[0]!=0) res[0][149]=a0;
  if (res[0]!=0) res[0][150]=a0;
  if (res[0]!=0) res[0][151]=a0;
  if (res[0]!=0) res[0][152]=a0;
  if (res[0]!=0) res[0][153]=a0;
  if (res[0]!=0) res[0][154]=a0;
  if (res[0]!=0) res[0][155]=a0;
  a1=arg[2]? arg[2][72] : 0;
  if (res[0]!=0) res[0][156]=a1;
  a1=arg[2]? arg[2][73] : 0;
  if (res[0]!=0) res[0][157]=a1;
  a1=arg[2]? arg[2][74] : 0;
  if (res[0]!=0) res[0][158]=a1;
  a1=arg[2]? arg[2][75] : 0;
  if (res[0]!=0) res[0][159]=a1;
  a1=arg[2]? arg[2][76] : 0;
  if (res[0]!=0) res[0][160]=a1;
  a1=arg[2]? arg[2][77] : 0;
  if (res[0]!=0) res[0][161]=a1;
  a1=arg[2]? arg[2][78] : 0;
  if (res[0]!=0) res[0][162]=a1;
  a1=arg[2]? arg[2][79] : 0;
  if (res[0]!=0) res[0][163]=a1;
  a1=arg[2]? arg[2][80] : 0;
  if (res[0]!=0) res[0][164]=a1;
  a1=arg[2]? arg[2][81] : 0;
  if (res[0]!=0) res[0][165]=a1;
  a1=arg[2]? arg[2][82] : 0;
  if (res[0]!=0) res[0][166]=a1;
  a1=arg[2]? arg[2][83] : 0;
  if (res[0]!=0) res[0][167]=a1;
  if (res[0]!=0) res[0][168]=a0;
  if (res[0]!=0) res[0][169]=a0;
  if (res[0]!=0) res[0][170]=a0;
  if (res[0]!=0) res[0][171]=a0;
  if (res[0]!=0) res[0][172]=a0;
  if (res[0]!=0) res[0][173]=a0;
  if (res[0]!=0) res[0][174]=a0;
  if (res[0]!=0) res[0][175]=a0;
  if (res[0]!=0) res[0][176]=a0;
  if (res[0]!=0) res[0][177]=a0;
  if (res[0]!=0) res[0][178]=a0;
  if (res[0]!=0) res[0][179]=a0;
  a1=arg[2]? arg[2][84] : 0;
  if (res[0]!=0) res[0][180]=a1;
  a1=arg[2]? arg[2][85] : 0;
  if (res[0]!=0) res[0][181]=a1;
  a1=arg[2]? arg[2][86] : 0;
  if (res[0]!=0) res[0][182]=a1;
  a1=arg[2]? arg[2][87] : 0;
  if (res[0]!=0) res[0][183]=a1;
  a1=arg[2]? arg[2][88] : 0;
  if (res[0]!=0) res[0][184]=a1;
  a1=arg[2]? arg[2][89] : 0;
  if (res[0]!=0) res[0][185]=a1;
  a1=arg[2]? arg[2][90] : 0;
  if (res[0]!=0) res[0][186]=a1;
  a1=arg[2]? arg[2][91] : 0;
  if (res[0]!=0) res[0][187]=a1;
  a1=arg[2]? arg[2][92] : 0;
  if (res[0]!=0) res[0][188]=a1;
  a1=arg[2]? arg[2][93] : 0;
  if (res[0]!=0) res[0][189]=a1;
  a1=arg[2]? arg[2][94] : 0;
  if (res[0]!=0) res[0][190]=a1;
  a1=arg[2]? arg[2][95] : 0;
  if (res[0]!=0) res[0][191]=a1;
  if (res[0]!=0) res[0][192]=a0;
  if (res[0]!=0) res[0][193]=a0;
  if (res[0]!=0) res[0][194]=a0;
  if (res[0]!=0) res[0][195]=a0;
  if (res[0]!=0) res[0][196]=a0;
  if (res[0]!=0) res[0][197]=a0;
  if (res[0]!=0) res[0][198]=a0;
  if (res[0]!=0) res[0][199]=a0;
  if (res[0]!=0) res[0][200]=a0;
  if (res[0]!=0) res[0][201]=a0;
  if (res[0]!=0) res[0][202]=a0;
  if (res[0]!=0) res[0][203]=a0;
  a1=arg[2]? arg[2][96] : 0;
  if (res[0]!=0) res[0][204]=a1;
  a1=arg[2]? arg[2][97] : 0;
  if (res[0]!=0) res[0][205]=a1;
  a1=arg[2]? arg[2][98] : 0;
  if (res[0]!=0) res[0][206]=a1;
  a1=arg[2]? arg[2][99] : 0;
  if (res[0]!=0) res[0][207]=a1;
  a1=arg[2]? arg[2][100] : 0;
  if (res[0]!=0) res[0][208]=a1;
  a1=arg[2]? arg[2][101] : 0;
  if (res[0]!=0) res[0][209]=a1;
  a1=arg[2]? arg[2][102] : 0;
  if (res[0]!=0) res[0][210]=a1;
  a1=arg[2]? arg[2][103] : 0;
  if (res[0]!=0) res[0][211]=a1;
  a1=arg[2]? arg[2][104] : 0;
  if (res[0]!=0) res[0][212]=a1;
  a1=arg[2]? arg[2][105] : 0;
  if (res[0]!=0) res[0][213]=a1;
  a1=arg[2]? arg[2][106] : 0;
  if (res[0]!=0) res[0][214]=a1;
  a1=arg[2]? arg[2][107] : 0;
  if (res[0]!=0) res[0][215]=a1;
  if (res[0]!=0) res[0][216]=a0;
  if (res[0]!=0) res[0][217]=a0;
  if (res[0]!=0) res[0][218]=a0;
  if (res[0]!=0) res[0][219]=a0;
  if (res[0]!=0) res[0][220]=a0;
  if (res[0]!=0) res[0][221]=a0;
  if (res[0]!=0) res[0][222]=a0;
  if (res[0]!=0) res[0][223]=a0;
  if (res[0]!=0) res[0][224]=a0;
  if (res[0]!=0) res[0][225]=a0;
  if (res[0]!=0) res[0][226]=a0;
  if (res[0]!=0) res[0][227]=a0;
  a1=arg[2]? arg[2][108] : 0;
  if (res[0]!=0) res[0][228]=a1;
  a1=arg[2]? arg[2][109] : 0;
  if (res[0]!=0) res[0][229]=a1;
  a1=arg[2]? arg[2][110] : 0;
  if (res[0]!=0) res[0][230]=a1;
  a1=arg[2]? arg[2][111] : 0;
  if (res[0]!=0) res[0][231]=a1;
  a1=arg[2]? arg[2][112] : 0;
  if (res[0]!=0) res[0][232]=a1;
  a1=arg[2]? arg[2][113] : 0;
  if (res[0]!=0) res[0][233]=a1;
  a1=arg[2]? arg[2][114] : 0;
  if (res[0]!=0) res[0][234]=a1;
  a1=arg[2]? arg[2][115] : 0;
  if (res[0]!=0) res[0][235]=a1;
  a1=arg[2]? arg[2][116] : 0;
  if (res[0]!=0) res[0][236]=a1;
  a1=arg[2]? arg[2][117] : 0;
  if (res[0]!=0) res[0][237]=a1;
  a1=arg[2]? arg[2][118] : 0;
  if (res[0]!=0) res[0][238]=a1;
  a1=arg[2]? arg[2][119] : 0;
  if (res[0]!=0) res[0][239]=a1;
  if (res[0]!=0) res[0][240]=a0;
  if (res[0]!=0) res[0][241]=a0;
  if (res[0]!=0) res[0][242]=a0;
  if (res[0]!=0) res[0][243]=a0;
  if (res[0]!=0) res[0][244]=a0;
  if (res[0]!=0) res[0][245]=a0;
  if (res[0]!=0) res[0][246]=a0;
  if (res[0]!=0) res[0][247]=a0;
  if (res[0]!=0) res[0][248]=a0;
  if (res[0]!=0) res[0][249]=a0;
  if (res[0]!=0) res[0][250]=a0;
  if (res[0]!=0) res[0][251]=a0;
  a1=arg[2]? arg[2][120] : 0;
  if (res[0]!=0) res[0][252]=a1;
  a1=arg[2]? arg[2][121] : 0;
  if (res[0]!=0) res[0][253]=a1;
  a1=arg[2]? arg[2][122] : 0;
  if (res[0]!=0) res[0][254]=a1;
  a1=arg[2]? arg[2][123] : 0;
  if (res[0]!=0) res[0][255]=a1;
  a1=arg[2]? arg[2][124] : 0;
  if (res[0]!=0) res[0][256]=a1;
  a1=arg[2]? arg[2][125] : 0;
  if (res[0]!=0) res[0][257]=a1;
  a1=arg[2]? arg[2][126] : 0;
  if (res[0]!=0) res[0][258]=a1;
  a1=arg[2]? arg[2][127] : 0;
  if (res[0]!=0) res[0][259]=a1;
  a1=arg[2]? arg[2][128] : 0;
  if (res[0]!=0) res[0][260]=a1;
  a1=arg[2]? arg[2][129] : 0;
  if (res[0]!=0) res[0][261]=a1;
  a1=arg[2]? arg[2][130] : 0;
  if (res[0]!=0) res[0][262]=a1;
  a1=arg[2]? arg[2][131] : 0;
  if (res[0]!=0) res[0][263]=a1;
  if (res[0]!=0) res[0][264]=a0;
  if (res[0]!=0) res[0][265]=a0;
  if (res[0]!=0) res[0][266]=a0;
  if (res[0]!=0) res[0][267]=a0;
  if (res[0]!=0) res[0][268]=a0;
  if (res[0]!=0) res[0][269]=a0;
  if (res[0]!=0) res[0][270]=a0;
  if (res[0]!=0) res[0][271]=a0;
  if (res[0]!=0) res[0][272]=a0;
  if (res[0]!=0) res[0][273]=a0;
  if (res[0]!=0) res[0][274]=a0;
  if (res[0]!=0) res[0][275]=a0;
  a0=arg[2]? arg[2][132] : 0;
  if (res[0]!=0) res[0][276]=a0;
  a0=arg[2]? arg[2][133] : 0;
  if (res[0]!=0) res[0][277]=a0;
  a0=arg[2]? arg[2][134] : 0;
  if (res[0]!=0) res[0][278]=a0;
  a0=arg[2]? arg[2][135] : 0;
  if (res[0]!=0) res[0][279]=a0;
  a0=arg[2]? arg[2][136] : 0;
  if (res[0]!=0) res[0][280]=a0;
  a0=arg[2]? arg[2][137] : 0;
  if (res[0]!=0) res[0][281]=a0;
  a0=arg[2]? arg[2][138] : 0;
  if (res[0]!=0) res[0][282]=a0;
  a0=arg[2]? arg[2][139] : 0;
  if (res[0]!=0) res[0][283]=a0;
  a0=arg[2]? arg[2][140] : 0;
  if (res[0]!=0) res[0][284]=a0;
  a0=arg[2]? arg[2][141] : 0;
  if (res[0]!=0) res[0][285]=a0;
  a0=arg[2]? arg[2][142] : 0;
  if (res[0]!=0) res[0][286]=a0;
  a0=arg[2]? arg[2][143] : 0;
  if (res[0]!=0) res[0][287]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_B(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_B_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_B_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_B_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_B_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_B_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_B_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_B_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_B_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_B_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_B_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_B_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_B_name_out(casadi_int i){
  switch (i) {
    case 0: return "B";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_B_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_B_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_B_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_linearization_c:(q[12],v[12],u[12],iH[12x12])->(c[24]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1+a2);
  a0=(a0*a1);
  a2=arg[3]? arg[3][12] : 0;
  a3=arg[2]? arg[2][1] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3+a4);
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][24] : 0;
  a4=arg[2]? arg[2][2] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4+a5);
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][36] : 0;
  a5=arg[2]? arg[2][3] : 0;
  a6=arg[1]? arg[1][3] : 0;
  a5=(a5+a6);
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][48] : 0;
  a6=arg[2]? arg[2][4] : 0;
  a7=arg[1]? arg[1][4] : 0;
  a6=(a6+a7);
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][60] : 0;
  a7=arg[2]? arg[2][5] : 0;
  a8=arg[1]? arg[1][5] : 0;
  a7=(a7+a8);
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][72] : 0;
  a8=arg[2]? arg[2][6] : 0;
  a9=arg[1]? arg[1][6] : 0;
  a8=(a8+a9);
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][84] : 0;
  a9=arg[2]? arg[2][7] : 0;
  a10=arg[1]? arg[1][7] : 0;
  a9=(a9+a10);
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][96] : 0;
  a10=arg[2]? arg[2][8] : 0;
  a11=arg[1]? arg[1][8] : 0;
  a10=(a10+a11);
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][108] : 0;
  a11=arg[2]? arg[2][9] : 0;
  a12=arg[1]? arg[1][9] : 0;
  a11=(a11+a12);
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][120] : 0;
  a12=arg[2]? arg[2][10] : 0;
  a13=arg[1]? arg[1][10] : 0;
  a12=(a12+a13);
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][132] : 0;
  a13=arg[2]? arg[2][11] : 0;
  a14=arg[1]? arg[1][11] : 0;
  a13=(a13+a14);
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][13] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][25] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][37] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][49] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][61] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][73] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][85] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][97] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][109] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][121] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][133] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][14] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][26] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][38] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][50] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][62] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][74] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][86] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][98] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][110] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][122] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][134] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[3]? arg[3][3] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][15] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][27] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][39] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][51] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][63] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][75] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][87] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][99] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][111] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][123] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][135] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[3]? arg[3][4] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][16] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][28] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][40] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][52] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][64] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][76] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][88] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][100] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][112] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][124] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][136] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[3]? arg[3][5] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][17] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][29] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][41] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][53] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][65] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][77] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][89] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][101] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][113] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][125] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][137] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[3]? arg[3][6] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][18] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][30] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][42] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][54] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][66] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][78] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][90] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][102] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][114] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][126] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][138] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][18]=a0;
  a0=arg[3]? arg[3][7] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][19] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][31] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][43] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][55] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][67] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][79] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][91] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][103] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][115] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][127] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][139] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][19]=a0;
  a0=arg[3]? arg[3][8] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][20] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][32] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][44] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][56] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][68] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][80] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][92] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][104] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][116] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][128] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][140] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[3]? arg[3][9] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][21] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][33] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][45] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][57] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][69] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][81] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][93] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][105] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][117] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][129] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][141] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][21]=a0;
  a0=arg[3]? arg[3][10] : 0;
  a0=(a0*a1);
  a2=arg[3]? arg[3][22] : 0;
  a2=(a2*a3);
  a0=(a0+a2);
  a2=arg[3]? arg[3][34] : 0;
  a2=(a2*a4);
  a0=(a0+a2);
  a2=arg[3]? arg[3][46] : 0;
  a2=(a2*a5);
  a0=(a0+a2);
  a2=arg[3]? arg[3][58] : 0;
  a2=(a2*a6);
  a0=(a0+a2);
  a2=arg[3]? arg[3][70] : 0;
  a2=(a2*a7);
  a0=(a0+a2);
  a2=arg[3]? arg[3][82] : 0;
  a2=(a2*a8);
  a0=(a0+a2);
  a2=arg[3]? arg[3][94] : 0;
  a2=(a2*a9);
  a0=(a0+a2);
  a2=arg[3]? arg[3][106] : 0;
  a2=(a2*a10);
  a0=(a0+a2);
  a2=arg[3]? arg[3][118] : 0;
  a2=(a2*a11);
  a0=(a0+a2);
  a2=arg[3]? arg[3][130] : 0;
  a2=(a2*a12);
  a0=(a0+a2);
  a2=arg[3]? arg[3][142] : 0;
  a2=(a2*a13);
  a0=(a0+a2);
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[3]? arg[3][11] : 0;
  a0=(a0*a1);
  a1=arg[3]? arg[3][23] : 0;
  a1=(a1*a3);
  a0=(a0+a1);
  a1=arg[3]? arg[3][35] : 0;
  a1=(a1*a4);
  a0=(a0+a1);
  a1=arg[3]? arg[3][47] : 0;
  a1=(a1*a5);
  a0=(a0+a1);
  a1=arg[3]? arg[3][59] : 0;
  a1=(a1*a6);
  a0=(a0+a1);
  a1=arg[3]? arg[3][71] : 0;
  a1=(a1*a7);
  a0=(a0+a1);
  a1=arg[3]? arg[3][83] : 0;
  a1=(a1*a8);
  a0=(a0+a1);
  a1=arg[3]? arg[3][95] : 0;
  a1=(a1*a9);
  a0=(a0+a1);
  a1=arg[3]? arg[3][107] : 0;
  a1=(a1*a10);
  a0=(a0+a1);
  a1=arg[3]? arg[3][119] : 0;
  a1=(a1*a11);
  a0=(a0+a1);
  a1=arg[3]? arg[3][131] : 0;
  a1=(a1*a12);
  a0=(a0+a1);
  a1=arg[3]? arg[3][143] : 0;
  a1=(a1*a13);
  a0=(a0+a1);
  if (res[0]!=0) res[0][23]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_c(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_c_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_c_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_c_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_c_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_c_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_c_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_c_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_c_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_c_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_c_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_c_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "u";
    case 3: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_c_name_out(casadi_int i){
  switch (i) {
    case 0: return "c";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_c_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_c_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_c_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
