function out1 = g_control_ForcesForComputedTorqueController(in1,in2)
%G_CONTROL_FORCESFORCOMPUTEDTORQUECONTROLLER
%    OUT1 = G_CONTROL_FORCESFORCOMPUTEDTORQUECONTROLLER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:10

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q2.*2.0;
t3 = q2+q3;
t4 = q3+t2;
t5 = sin(t4);
t6 = q3.*2.0;
t7 = t2+t6;
t8 = sin(t7);
t9 = t8.*(9.0./5.0);
t10 = sin(t3);
t11 = t10.*(3.6e1./5.0);
t12 = sin(q2);
t13 = sin(q3);
t14 = cos(q1);
out1 = [v1.*(1.0./2.0)-v1.*(v2.*(t5.*(3.6e1./5.0)+t9+t11+t12.*(1.08e2./5.0)+sin(t2).*9.0).*(1.0./2.0)+v3.*(t5.*(1.8e1./5.0)+t9+t11+t13.*(1.8e1./5.0)).*(1.0./2.0))-sin(q1).*(cos(q2).*3.0+cos(t3)+5.0).*(2.94e2./5.0);v2.*(1.0./2.0)-t14.*(t10+t12.*3.0).*(2.94e2./5.0)-t13.*v3.*(v2.*2.0+v3).*(9.0./5.0);v3.*(1.0./2.0)-t10.*t14.*(2.94e2./5.0)-t13.*v2.*v3.*(9.0./5.0)];
