function out1 = g_dynamics_Linearization_RHS_c(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_C
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:12

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
u2 = in2(2,:);
u3 = in2(3,:);
t2 = sin(s1);
t3 = s2+s3;
t4 = sin(t3);
t5 = sin(s2);
t6 = cos(t3);
t7 = cos(s2);
t8 = t4.*2.94e2;
t9 = cos(s1);
t10 = t5.*8.82e2;
t11 = t7.*3.0;
out1 = [0.0;0.0;0.0;t2.*(t6+t11+5.0).*(2.94e2./5.0)-s1.*t9.*(t6.*2.94e2+t7.*8.82e2+t4.*u3.*5.0+t5.*u2.*5.0-t5.*u3.*5.0+1.47e3).*(1.0./5.0)+s3.*t2.*(t8-t6.*u3.*5.0).*(1.0./5.0)+s2.*t2.*(t8+t10-t6.*u3.*5.0-t7.*u2.*5.0+t7.*u3.*5.0).*(1.0./5.0)+t2.*t4.*u3-t2.*t5.*u3-t2.*u3.*(t4-t5);t9.*(t4+t5.*3.0).*(2.94e2./5.0)+s1.*t2.*(t8+t10+u2.*5.0).*(1.0./5.0)-s2.*t9.*(t6+t11).*(2.94e2./5.0)-s3.*t6.*t9.*(2.94e2./5.0);t4.*t9.*(2.94e2./5.0)-s2.*t6.*t9.*(2.94e2./5.0)-s3.*t6.*t9.*(2.94e2./5.0)+s1.*t2.*(t8+u3.*5.0).*(1.0./5.0)];
