function out1 = g_dynamics_Linearization_RHS_B(in1)
%G_DYNAMICS_LINEARIZATION_RHS_B
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_B(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:11

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
t2 = sin(s1);
t3 = sin(s2);
t4 = cos(s1);
out1 = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,t2.*t3,t4,0.0,0.0,0.0,0.0,-t2.*(t3-sin(s2+s3)),0.0,t4],[6,3]);
