function F = g_dynamics_LagrangeMultiplier_ConstraintJacobian(in1)
%G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINTJACOBIAN
%    F = G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINTJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:13

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2+q3;
t3 = cos(t2);
t4 = t3.*(3.0./5.0);
t5 = cos(q2);
t6 = sin(t2);
t7 = cos(q1);
F = reshape([0.0,sin(q1).*(t3+t5+1.0).*(-3.0./5.0),t4+t5.*(3.0./5.0),t7.*(t6+sin(q2)).*(-3.0./5.0),t4,t6.*t7.*(-3.0./5.0)],[2,3]);
