function out1 = g_dynamics_JSIM(in1)
%G_DYNAMICS_JSIM
%    OUT1 = G_DYNAMICS_JSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:09

q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2.*2.0;
t3 = cos(q3);
t4 = t3.*(1.8e1./5.0);
t5 = t4+1.4e1./5.0;
out1 = reshape([t4+cos(q3.*2.0+t2).*(9.0./1.0e1)+cos(q2+q3).*(3.6e1./5.0)+cos(q3+t2).*(1.8e1./5.0)+cos(q2).*(1.08e2./5.0)+cos(t2).*(9.0./2.0)+1.23e2./5.0,0.0,0.0,0.0,t3.*(3.6e1./5.0)+6.4e1./5.0,t5,0.0,t5,1.4e1./5.0],[3,3]);
