function out1 = g_dynamics_Linearization_RHS_A(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_A
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:11

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
u2 = in2(2,:);
u3 = in2(3,:);
t2 = s2+s3;
t3 = sin(s2);
t4 = sin(t2);
t5 = cos(t2);
t6 = cos(s2);
t7 = sin(s1);
t8 = t4.*2.94e2;
t9 = t3.*8.82e2;
t10 = cos(s1);
t11 = t5.*t10.*(2.94e2./5.0);
out1 = reshape([0.0,0.0,0.0,t10.*(t5.*2.94e2+t6.*8.82e2+t3.*u2.*5.0-t3.*u3.*5.0+t4.*u3.*5.0+1.47e3).*(1.0./5.0),t7.*(t8+t9+u2.*5.0).*(-1.0./5.0),t7.*(t8+u3.*5.0).*(-1.0./5.0),0.0,0.0,0.0,t7.*(t8+t9-t5.*u3.*5.0-t6.*u2.*5.0+t6.*u3.*5.0).*(-1.0./5.0),t10.*(t5+t6.*3.0).*(2.94e2./5.0),t11,0.0,0.0,0.0,t7.*(t8-t5.*u3.*5.0).*(-1.0./5.0),t11,t11,1.0,0.0,0.0,-1.0./2.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0./2.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0./2.0],[6,6]);
