function Constraint = g_dynamics_LagrangeMultiplier_Constraint(in1)
%G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINT
%    CONSTRAINT = G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:13

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q2);
t3 = cos(q1);
t4 = cos(q2);
t5 = cos(q3);
t6 = sin(q3);
Constraint = [t2.*(3.0./5.0)+t2.*t5.*(3.0./5.0)+t4.*t6.*(3.0./5.0)-1.0;t3.*(3.0./5.0)+t3.*t4.*(3.0./5.0)-t2.*t3.*t6.*(3.0./5.0)+t3.*t4.*t5.*(3.0./5.0)+1.0];
