function SecondJacobian = g_dynamics_LagrangeMultiplier_ConstraintSecondJacobian(in1,in2)
%G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINTSECONDJACOBIAN
%    SECONDJACOBIAN = G_DYNAMICS_LAGRANGEMULTIPLIER_CONSTRAINTSECONDJACOBIAN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:13

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q2+q3;
t3 = sin(t2);
t4 = sin(q1);
t5 = sin(q2);
t6 = cos(t2);
t7 = cos(q1);
t8 = cos(q2);
t9 = t3+t5;
SecondJacobian = reshape([0.0,t7.*v1.*(t6+t8+1.0).*(-3.0./5.0)+t3.*t4.*v3.*(3.0./5.0)+t4.*t9.*v2.*(3.0./5.0),t3.*v3.*(-3.0./5.0)-v2.*(t3.*(3.0./5.0)+t5.*(3.0./5.0)),t7.*v2.*(t6+t8).*(-3.0./5.0)+t4.*t9.*v1.*(3.0./5.0)-t6.*t7.*v3.*(3.0./5.0),t3.*(v2+v3).*(-3.0./5.0),t3.*t4.*v1.*(3.0./5.0)-t6.*t7.*v2.*(3.0./5.0)-t6.*t7.*v3.*(3.0./5.0)],[2,3]);
