function out1 = g_dynamics_Linearization_SSIM(in1)
%G_DYNAMICS_LINEARIZATION_SSIM
%    OUT1 = G_DYNAMICS_LINEARIZATION_SSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Jun-2020 18:25:11

s2 = in1(2,:);
s3 = in1(3,:);
s5 = in1(5,:);
s6 = in1(6,:);
t2 = s2.*2.0;
t3 = s3+t2;
t4 = sin(t3);
t5 = s3.*2.0;
t6 = t2+t5;
t7 = sin(t6);
t8 = t7.*(9.0./5.0);
t9 = s2+s3;
t10 = sin(t9);
t11 = t10.*(3.6e1./5.0);
t12 = sin(s3);
t13 = cos(s3);
t14 = t13.*(1.8e1./5.0);
t15 = t14+1.4e1./5.0;
out1 = reshape([1.0,0.0,0.0,-s5.*(t4.*(3.6e1./5.0)+t8+t11+sin(s2).*(1.08e2./5.0)+sin(t2).*9.0)-s6.*(t4.*(1.8e1./5.0)+t8+t11+t12.*(1.8e1./5.0)),0.0,0.0,0.0,1.0,0.0,0.0,s6.*t12.*(-3.6e1./5.0),s6.*t12.*(-1.8e1./5.0),0.0,0.0,1.0,0.0,s6.*t12.*(-1.8e1./5.0),0.0,0.0,0.0,0.0,t14+cos(s2).*(1.08e2./5.0)+cos(t2).*(9.0./2.0)+cos(t3).*(1.8e1./5.0)+cos(t6).*(9.0./1.0e1)+cos(t9).*(3.6e1./5.0)+1.23e2./5.0,0.0,0.0,0.0,0.0,0.0,0.0,t13.*(3.6e1./5.0)+6.4e1./5.0,t15,0.0,0.0,0.0,0.0,t15,1.4e1./5.0],[6,6]);
