function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 18:19:44

q1 = in1(1,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
t2 = sin(q1);
t3 = q1.*2.0;
t4 = q1.*3.0;
t5 = sin(t3);
t6 = sin(t4);
c = [t2.*(3.43e+2./2.0)+t5.*2.45e+2+t6.*(4.41e+2./2.0)-v1+sin(q1.*4.0).*9.8e+1-(v1.^2.*(t2.*1.0e+2+t5.*8.5e+1+t6.*3.0e+1))./2.0;-v2;-v3;-v4];
