function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 18:19:43

q1 = in1(1,:);
t2 = cos(q1);
H = reshape([t2.*7.0e+1+t2.^2.*8.5e+1+t2.^3.*4.0e+1+1.55e+2./4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
