function T = g_dynamics_T(in1)
%G_DYNAMICS_T
%    T = G_DYNAMICS_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Dec-2020 18:19:44

T = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
