function out1 = g_dynamics_ControlMap(in1)
%G_DYNAMICS_CONTROLMAP
%    OUT1 = G_DYNAMICS_CONTROLMAP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    01-Oct-2020 20:34:05

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.^2;
t7 = t3.^2;
t8 = t4.^2;
t9 = t5.^2;
out1 = reshape([t6+t8,0.0,0.0,-t6-t8,t7+t9,0.0,0.0,-t7-t9,cos(q3).^2+sin(q3).^2],[3,3]);
