function out1 = g_dynamics_Linearization_RHS_A(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_A
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_A(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    14-Nov-2018 09:10:20

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
out1 = reshape([0.0,0.0,0.0,cos(s1).*2.94e2,0.0,0.0,0.0,0.0,0.0,0.0,cos(s2).*(8.82e2./5.0),0.0,0.0,0.0,0.0,0.0,0.0,cos(s3).*(2.94e2./5.0),1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0],[6,6]);
