function out1 = g_dynamics_JSIM(in1)
%G_DYNAMICS_JSIM
%    OUT1 = G_DYNAMICS_JSIM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 16:32:24

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.^2;
t9 = t3.^2;
t10 = t4.^2;
t11 = t5.^2;
t12 = t6.^2;
t13 = t7.^2;
t14 = t2.*t4.*(1.8e+1./5.0);
t15 = t3.*t4.*(1.8e+1./5.0);
t16 = t2.*t3.*(5.4e+1./5.0);
t17 = t5.*t7.*(1.8e+1./5.0);
t18 = t6.*t7.*(1.8e+1./5.0);
t19 = t5.*t6.*(5.4e+1./5.0);
t20 = t14+t17;
t21 = t15+t18;
t22 = t16+t19;
out1 = reshape([t8.*(8.1e+1./5.0)+t11.*(8.1e+1./5.0)+(t8+t11).^2,t22,t20,t22,t9.*9.0+t12.*9.0+(t9+t12).^2,t21,t20,t21,t10.*(9.0./5.0)+t13.*(9.0./5.0)+(t10+t13).^2],[3,3]);
