function out1 = g_dynamics_RHS(in1,in2,in3)
%G_DYNAMICS_RHS
%    OUT1 = G_DYNAMICS_RHS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Sep-2020 20:05:13

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.^2;
t9 = t3.^2;
t10 = t5.^2;
t11 = t6.^2;
t12 = t2.*t7.*(1.8e+1./5.0);
t13 = t4.*t5.*(1.8e+1./5.0);
t14 = t3.*t7.*(1.8e+1./5.0);
t15 = t4.*t6.*(1.8e+1./5.0);
t16 = t2.*t6.*(5.4e+1./5.0);
t17 = t3.*t5.*(5.4e+1./5.0);
t18 = t8+t10;
t19 = t9+t11;
t20 = -t13;
t21 = -t15;
t22 = -t17;
t23 = t12+t20;
t24 = t14+t21;
t25 = t16+t22;
t26 = (t23.*v1)./2.0;
t27 = (t23.*v3)./2.0;
t28 = (t24.*v2)./2.0;
t29 = (t24.*v3)./2.0;
t30 = (t25.*v1)./2.0;
t31 = (t25.*v2)./2.0;
t32 = -t27;
t33 = -t29;
t34 = -t31;
t35 = t26+t32;
t36 = t28+t33;
t37 = t30+t34;
out1 = [t5.*2.94e+2-v1+t18.*u1-t18.*u2-t35.*v3-t37.*v2;t6.*(8.82e+2./5.0)-v2+t19.*u2-t19.*u3-t37.*v1-t36.*v3;t7.*(2.94e+2./5.0)-v3-t35.*v1-t36.*v2+u3.*(t4.^2+t7.^2)];
