function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    24-Apr-2018 22:38:15

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
t3 = q1+q2;
Task = [sin(q1).*(1.0./2.0)+sin(t2).*(1.0./1.0e1)+sin(t3).*(3.0./1.0e1);cos(q1).*(1.0./2.0)+cos(t2).*(1.0./1.0e1)+cos(t3).*(3.0./1.0e1);t2];
