close all; clear classes;

InitialPosition = SRD_get('InitialPosition');

Handler_State = SRD_get_handler__state('InitialPosition', InitialPosition, ...
    'InitialVelocity', zeros(size(InitialPosition)));

Handler_IK_Solution = SRD_get('Handler_IK_Solution');
Handler_dynamics_generalized_coordinates_model = SRD_get('Handler_dynamics_generalized_coordinates_model');

dt = 0.001;
tf = Handler_IK_Solution.TimeExpiration;
% tf = 0.3;

Handler_Simulation = SRD_get_handler__Simulation(...
    'TimeLog', 0:dt:tf);


Handler_InverseDynamics = SRD_get_handler__InverseDynamics_Vanilla__desired_trajectory(...
    'Handler_ControlInput', Handler_IK_Solution, ...
    'Handler_dynamics_generalized_coordinates_model', Handler_dynamics_generalized_coordinates_model, ...
    'Handler_Simulation', Handler_Simulation);

Handler_ComputedTorqueController = SRD_get_handler__ComputedTorqueController(...
    'Handler_State', Handler_State, ...
    'Handler_ControlInput', Handler_IK_Solution, ...
    'Handler_dynamics_generalized_coordinates_model', Handler_dynamics_generalized_coordinates_model, ...
    'Handler_Simulation', Handler_Simulation, ...
    'Handler_InverseDynamics', Handler_InverseDynamics, ...
    'Kp', 500*eye(Handler_IK_Solution.dof_robot), ...
    'Kd', 100*eye(Handler_IK_Solution.dof_robot));




Handler_solver_Taylor = SRD_get_handler__solver_Taylor(...
    'Handler_State', Handler_State, ...
    'Handler_Controller', Handler_ComputedTorqueController, ...
    'Handler_dynamics_generalized_coordinates_model', Handler_dynamics_generalized_coordinates_model, ...
    'Handler_Simulation', Handler_Simulation);


Handler_State_Logger_vanilla = SRD_get_handler__State_Logger__vanilla(...
    'Handler_State', Handler_State, ...
    'Handler_Simulation', Handler_Simulation);


Handler_Simulation.ControllerArray = {Handler_InverseDynamics; Handler_ComputedTorqueController};
Handler_Simulation.SolverArray = {Handler_solver_Taylor};
Handler_Simulation.LoggerArray = {Handler_State_Logger_vanilla};

Handler_Simulation.Simulate();


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


figure('Color', 'w', 'Name', 'Positions');

subplot(1, 2, 1)
SRDgraphic_PlotGeneric(Handler_Simulation.TimeLog, Handler_State_Logger_vanilla.Log.q, ...
    'NewFigure', false, 'FigureName', 'Generic', ...
    'LableVariable', 'q', 'Title', []);

subplot(1, 2, 2)
SRDgraphic_PlotGeneric(Handler_Simulation.TimeLog, Handler_State_Logger_vanilla.Log.v, ...
    'NewFigure', false, 'FigureName', 'Generic', ...
    'LableVariable', 'v', 'Title', []);

drawnow;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%

ToAnimate = true;

if ToAnimate
DrawRobot_function = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'SimulationEngine', [], ...
    'FileName_visuals_config', []); %use default visuals

SRD__animate__vanilla('Handler_Simulation', Handler_Simulation, ...
    'Handler_Logger', Handler_State_Logger_vanilla, ...
    'AnimationTimeLog', 0:10*dt:tf, ...
    'DrawRobot_function', DrawRobot_function, ...
    'NewFigure', true, ...
    'FigureName', 'Animation', ...
    'FileName_visuals_config', []);
end



