close all;

SRD = SRDuserinterface;

%here we set up default visual settings
SRD.SetupVisuals('AxisLimits', [-1; 1; -1; 1; -1; 1], ...
    'ViewAngle', [-37.5, 30], ...
    'ToDrawMeshes', false, ...
    'DrawRobot_Default_RobotColor', [0.6 0.3 0], ...
    'DrawRobot_Default_EdgeAlpha', 0.3, ...
    'DrawRobot_Default_FaceAlpha', 1, ...
    'DrawRobot_Default_LineWidth', 1.5, ...
    'DrawRobot_STL_FaceColor', [0.8 0.8 1.0], ...
    'DrawRobot_STL_EdgeColor', 'none', ...
    'DrawRobot_STL_FaceLighting', 'gouraud', ...
    'DrawRobot_STL_AmbientStrength', 0.15, ...
    'ToDrawFrames', false, ...
    'DrawRobot_Frame_Scale', 0.2, ...
    'DrawRobot_Frame_LineWidth', 1, ...
    'FileName_visuals_config', []);

%here we set up custom visual settings in a different file
SRD.SetupVisuals('AxisLimits', [-1; 1; -1; 1; -1; 1], ...
    'ViewAngle', [-37.5, 30], ...
    'ToDrawMeshes', false, ...
    'DrawRobot_Default_RobotColor', [0.6 0.3 0], ...
    'DrawRobot_Default_EdgeAlpha', 0.2, ...
    'DrawRobot_Default_FaceAlpha', 1, ...
    'DrawRobot_Default_LineWidth', 2.5, ...
    'DrawRobot_STL_FaceColor', [0.8 0.8 1.0], ...
    'DrawRobot_STL_EdgeColor', 'none', ...
    'DrawRobot_STL_FaceLighting', 'gouraud', ...
    'DrawRobot_STL_AmbientStrength', 0.15, ...
    'ToDrawFrames', true, ...
    'DrawRobot_Frame_Scale', 0.2, ...
    'DrawRobot_Frame_LineWidth', 1, ...
    'FileName_visuals_config', 'datafile_visuals_config');



figure('Color', 'w')
subplot(2, 2, 1);

DrawRobot_function_1 = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawInitialPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'SimulationEngine', [], ...
    'FileName_visuals_config', []); %use default visuals
DrawRobot_function_1([]);
axis equal;



subplot(2, 2, 2);

SRD = SRDuserinterface;
SimulationEngine = SRD.GetSimulationEngine();

DrawRobot_function_2 = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawCurrentPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'SimulationEngine', SimulationEngine, ...
    'FileName_visuals_config', 'datafile_visuals_config'); %use custom visuals

SimulationEngine.Update(randn(SimulationEngine.dof, 1));
DrawRobot_function_2([]);
axis equal;



subplot(2, 2, 3);

DrawRobot_function_3 = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'SimulationEngine', SimulationEngine, ...
    'FileName_visuals_config', 'datafile_visuals_config'); %use custom visuals

DrawRobot_function_3(randn(SimulationEngine.dof, 1), []);
DrawRobot_function_3(randn(SimulationEngine.dof, 1), []);
DrawRobot_function_3(randn(SimulationEngine.dof, 1), []);
axis equal;



subplot(2, 2, 4);

DrawRobot_function_3 = SRD_DrawRobot_get_function('DrawRobot_Type', 'Custom', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', @my_DrawRobot_fnc, ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'SimulationEngine', SimulationEngine, ...
    'FileName_visuals_config', 'datafile_visuals_config'); %use custom visuals

DrawRobot_function_3(randn(SimulationEngine.dof, 1), []);
axis equal;


function h = my_DrawRobot_fnc(SimulationEngine, old_h)
h = SRD_DrawRobot_Default(SimulationEngine, old_h, ...
    [1 0 0], 1, 1, 1);

for i = 1:5
    shift = 0.3*randn(3, 1);
    [X,Y,Z] = sphere(10);
    scale = 0.3*rand(3, 1);
    
    surf(scale(1)*X+shift(1), scale(2)*Y+shift(2), scale(3)*Z+shift(3));
end
end

