function Task = g_Constraint(in1)
%G_CONSTRAINT
%    TASK = G_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Dec-2020 12:44:55

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
t3 = q1+q2;
Task = [0.0;sin(q1).*(-1.0./2.0)-sin(t2).*(1.0./2.0)-sin(t3).*(1.0./2.0);cos(q1).*(1.0./2.0)+cos(t2).*(1.0./2.0)+cos(t3).*(1.0./2.0)];
