function TaskJacobian = g_Constraint_Jacobian(in1)
%G_CONSTRAINT_JACOBIAN
%    TASKJACOBIAN = G_CONSTRAINT_JACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Oct-2020 19:42:20

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2;
t3 = q3+t2;
t4 = sin(t2);
t5 = sin(t3);
t6 = t4./2.0;
t7 = -t6;
t8 = t5./2.0;
t9 = -t8;
TaskJacobian = [t7+t9-sin(q1)./2.0,t7+t9,t9];
