function Task = g_Constraint(in1)
%G_CONSTRAINT
%    TASK = G_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 16:34:01

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Task = sin(q1).*(3.0./5.0)+sin(q2).*(3.0./5.0)+sin(q3).*(3.0./5.0);
