function Task = g_Constraint(in1)
%G_CONSTRAINT
%    TASK = G_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Dec-2020 12:35:49

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Task = sin(q1+q2+q3).*(-1.0./2.0)-sin(q1+q2).*(1.0./2.0)-sin(q1).*(1.0./2.0);
