function TaskJacobian_derivative = g_Constraint_Jacobian_derivative(in1,in2)
%G_CONSTRAINT_JACOBIAN_DERIVATIVE
%    TASKJACOBIAN_DERIVATIVE = G_CONSTRAINT_JACOBIAN_DERIVATIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Nov-2020 19:17:25

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q1+q2+q3;
t3 = cos(t2);
t4 = t3.*(1.0./2.0);
t5 = q1+q2;
t6 = cos(t5);
t7 = t6.*(1.0./2.0);
t8 = t4+t7;
TaskJacobian_derivative = [t3.*v3.*(-1.0./2.0)-t8.*v2-v1.*(t4+t7+cos(q1).*(1.0./2.0)),t3.*v3.*(-1.0./2.0)-t8.*v1-t8.*v2,t3.*(v1+v2+v3).*(-1.0./2.0)];
