function out1 = g_control_ForcesForComputedTorqueController(in1,in2)
%G_CONTROL_FORCESFORCOMPUTEDTORQUECONTROLLER
%    OUT1 = G_CONTROL_FORCESFORCOMPUTEDTORQUECONTROLLER(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Sep-2020 14:52:25

v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
v4 = in2(4,:);
v5 = in2(5,:);
v6 = in2(6,:);
out1 = [v1;v2;v3;v4;v5;v6];
