function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Sep-2020 14:38:39

q1 = in1(1,:);
q2 = in1(2,:);
Task = [NaN;q1+q2];
