function out1 = g_dynamics_Linearization_RHS_c(in1,in2)
%G_DYNAMICS_LINEARIZATION_RHS_C
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Aug-2020 16:07:39

s1 = in1(1,:);
s2 = in1(2,:);
t2 = cos(s2);
t3 = sin(s2);
out1 = [0.0;0.0;sin(s1).*2.94e2-s1.*cos(s1).*2.94e2;t2.*2.011078442754932e1+t3.*1.211460738977886e2-s2.*(t2.*1.211460738977886e2-t3.*2.011078442754932e1)];
