function out1 = g_dynamics_ControlMap(in1)
%G_DYNAMICS_CONTROLMAP
%    OUT1 = G_DYNAMICS_CONTROLMAP(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Aug-2020 16:07:38

out1 = reshape([1.0,0.0,-1.0,1.0],[2,2]);
