function out1 = g_dynamics_Linearization_RHS_B(in1)
%G_DYNAMICS_LINEARIZATION_RHS_B
%    OUT1 = G_DYNAMICS_LINEARIZATION_RHS_B(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Aug-2020 16:07:39

out1 = reshape([0.0,0.0,1.0,0.0,0.0,0.0,-1.0,1.0],[4,2]);
