function J2 = g_InverseKinematics_J2(in1,in2)
%G_INVERSEKINEMATICS_J2
%    J2 = G_INVERSEKINEMATICS_J2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    24-Apr-2018 22:38:16

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = q1+q2+q3;
t3 = sin(t2);
t4 = t3.*(1.0./1.0e1);
t5 = q1+q2;
t6 = sin(t5);
t7 = t6.*(3.0./1.0e1);
t8 = t4+t7;
t9 = cos(t2);
t10 = t9.*(1.0./1.0e1);
t11 = cos(t5);
t12 = t11.*(3.0./1.0e1);
t13 = t10+t12;
t14 = v1+v2+v3;
J2 = reshape([t3.*v3.*(-1.0./1.0e1)-t8.*v2-v1.*(t4+t7+sin(q1).*(1.0./2.0)),t9.*v3.*(-1.0./1.0e1)-t13.*v2-v1.*(t10+t12+cos(q1).*(1.0./2.0)),0.0,t3.*v3.*(-1.0./1.0e1)-t8.*v1-t8.*v2,t9.*v3.*(-1.0./1.0e1)-t13.*v1-t13.*v2,0.0,t3.*t14.*(-1.0./1.0e1),t9.*t14.*(-1.0./1.0e1),0.0],[3,3]);
