/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_Constraints_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 6, 0, 3, 3, 3, 3, 3, 3, 0, 1, 2};

/* g_Constraint:(q[6])->(Task[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.9999999999999988e-02;
  a1=4.3698782634577347e-08;
  a2=arg[0]? arg[0][0] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=-3.9412917374193057e-15;
  a6=sin(a2);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a0*a4);
  a7=6.1540914084965174e-19;
  a8=cos(a2);
  a5=(a5*a8);
  a2=sin(a2);
  a1=(a1*a2);
  a5=(a5-a1);
  a5=(a7*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][0]=a4;
  a4=1.0000000000000001e-01;
  a5=-8.7397565269154959e-08;
  a1=(a5*a3);
  a9=-9.9999999999999623e-01;
  a10=(a9*a6);
  a1=(a1+a10);
  a1=(a0*a1);
  a9=(a9*a8);
  a5=(a5*a2);
  a9=(a9-a5);
  a9=(a7*a9);
  a1=(a1+a9);
  a4=(a4+a1);
  if (res[0]!=0) res[0][1]=a4;
  a4=-1.4999999999999999e-01;
  a1=-9.9999999999999523e-01;
  a3=(a1*a3);
  a9=8.7397565269154880e-08;
  a6=(a9*a6);
  a3=(a3+a6);
  a0=(a0*a3);
  a9=(a9*a8);
  a1=(a1*a2);
  a9=(a9-a1);
  a7=(a7*a9);
  a0=(a0+a7);
  a4=(a4+a0);
  if (res[0]!=0) res[0][2]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_Constraint_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_Constraint_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_Constraint_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_name_out(casadi_int i){
  switch (i) {
    case 0: return "Task";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_Constraint_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_Constraint_Jacobian:(q[6])->(TaskJacobian[3x6,3nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.9999999999999988e-02;
  a1=-3.9412917374193057e-15;
  a2=arg[0]? arg[0][0] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=4.3698782634577347e-08;
  a6=sin(a2);
  a7=(a5*a6);
  a4=(a4-a7);
  a4=(a0*a4);
  a7=6.1540914084965174e-19;
  a8=sin(a2);
  a1=(a1*a8);
  a2=cos(a2);
  a5=(a5*a2);
  a1=(a1+a5);
  a1=(a7*a1);
  a4=(a4-a1);
  if (res[0]!=0) res[0][0]=a4;
  a4=-9.9999999999999623e-01;
  a1=(a4*a3);
  a5=-8.7397565269154959e-08;
  a9=(a5*a6);
  a1=(a1-a9);
  a1=(a0*a1);
  a4=(a4*a8);
  a5=(a5*a2);
  a4=(a4+a5);
  a4=(a7*a4);
  a1=(a1-a4);
  if (res[0]!=0) res[0][1]=a1;
  a1=8.7397565269154880e-08;
  a3=(a1*a3);
  a4=-9.9999999999999523e-01;
  a6=(a4*a6);
  a3=(a3-a6);
  a0=(a0*a3);
  a1=(a1*a8);
  a4=(a4*a2);
  a1=(a1+a4);
  a7=(a7*a1);
  a0=(a0-a7);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_Jacobian_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_Jacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_Constraint_Jacobian_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_Jacobian_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_Jacobian_name_out(casadi_int i){
  switch (i) {
    case 0: return "TaskJacobian";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_Jacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_Jacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_Constraint_Jacobian_derivative:(q[6],v[6])->(TaskJacobian_derivative[3x6,3nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.9999999999999988e-02;
  a1=-3.9412917374193057e-15;
  a2=arg[0]? arg[0][0] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a5=4.3698782634577347e-08;
  a6=cos(a2);
  a7=(a5*a6);
  a4=(a4+a7);
  a4=(a0*a4);
  a7=6.1540914084965174e-19;
  a8=cos(a2);
  a1=(a1*a8);
  a2=sin(a2);
  a5=(a5*a2);
  a1=(a1-a5);
  a1=(a7*a1);
  a4=(a4+a1);
  a1=arg[1]? arg[1][0] : 0;
  a4=(a4*a1);
  a4=(-a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=-9.9999999999999623e-01;
  a5=(a4*a3);
  a9=-8.7397565269154959e-08;
  a10=(a9*a6);
  a5=(a5+a10);
  a5=(a0*a5);
  a4=(a4*a8);
  a9=(a9*a2);
  a4=(a4-a9);
  a4=(a7*a4);
  a5=(a5+a4);
  a5=(a5*a1);
  a5=(-a5);
  if (res[0]!=0) res[0][1]=a5;
  a5=8.7397565269154880e-08;
  a3=(a5*a3);
  a4=-9.9999999999999523e-01;
  a6=(a4*a6);
  a3=(a3+a6);
  a0=(a0*a3);
  a5=(a5*a8);
  a4=(a4*a2);
  a5=(a5-a4);
  a7=(a7*a5);
  a0=(a0+a7);
  a0=(a0*a1);
  a0=(-a0);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_derivative(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_derivative_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_derivative_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_derivative_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_derivative_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_derivative_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_derivative_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_Constraint_Jacobian_derivative_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_Jacobian_derivative_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int g_Constraint_Jacobian_derivative_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_Constraint_Jacobian_derivative_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_Jacobian_derivative_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_Constraint_Jacobian_derivative_name_out(casadi_int i){
  switch (i) {
    case 0: return "TaskJacobian_derivative";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_Jacobian_derivative_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_Constraint_Jacobian_derivative_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_Constraint_Jacobian_derivative_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
