/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_dynamics_linearization_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[24] = {6, 3, 0, 6, 12, 18, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* g_linearization_A:(q[3],v[3],u[3],iH[3x3])->(A[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=arg[1]? arg[1][0] : 0;
  a2=5.0000000000000000e-01;
  a3=20.;
  a4=2.9999999999999999e-01;
  a5=arg[0]? arg[0][0] : 0;
  a6=cos(a5);
  a6=(a4*a6);
  a7=(a3*a6);
  a8=cos(a5);
  a8=(a4*a8);
  a9=(a7*a8);
  a10=sin(a5);
  a10=(a4*a10);
  a11=sin(a5);
  a11=(a4*a11);
  a12=(a3*a11);
  a12=(a10*a12);
  a9=(a9-a12);
  a12=(a3*a8);
  a12=(a6*a12);
  a13=(a3*a10);
  a11=(a13*a11);
  a12=(a12-a11);
  a9=(a9+a12);
  a12=cos(a5);
  a12=(a4*a12);
  a11=cos(a5);
  a11=(a4*a11);
  a14=(a3*a11);
  a14=(a12*a14);
  a15=sin(a5);
  a15=(a4*a15);
  a16=(a3*a15);
  a17=sin(a5);
  a17=(a4*a17);
  a18=(a16*a17);
  a14=(a14-a18);
  a18=(a3*a12);
  a11=(a18*a11);
  a17=(a3*a17);
  a17=(a15*a17);
  a11=(a11-a17);
  a14=(a14+a11);
  a9=(a9-a14);
  a14=5.9999999999999998e-01;
  a11=cos(a5);
  a11=(a14*a11);
  a17=(a3*a11);
  a19=cos(a5);
  a19=(a14*a19);
  a20=(a17*a19);
  a21=sin(a5);
  a21=(a14*a21);
  a22=sin(a5);
  a22=(a14*a22);
  a23=(a3*a22);
  a24=(a21*a23);
  a20=(a20-a24);
  a24=(a3*a19);
  a25=(a11*a24);
  a26=(a3*a21);
  a27=(a26*a22);
  a25=(a25-a27);
  a20=(a20+a25);
  a25=cos(a5);
  a25=(a14*a25);
  a27=cos(a5);
  a27=(a14*a27);
  a28=(a3*a27);
  a29=(a25*a28);
  a30=sin(a5);
  a30=(a14*a30);
  a31=(a3*a30);
  a32=sin(a5);
  a32=(a14*a32);
  a33=(a31*a32);
  a29=(a29-a33);
  a33=(a3*a25);
  a34=(a33*a27);
  a35=(a3*a32);
  a36=(a30*a35);
  a34=(a34-a36);
  a29=(a29+a34);
  a20=(a20-a29);
  a9=(a9+a20);
  a20=cos(a5);
  a20=(a14*a20);
  a29=(a3*a20);
  a34=cos(a5);
  a34=(a14*a34);
  a36=(a29*a34);
  a37=sin(a5);
  a37=(a14*a37);
  a38=sin(a5);
  a38=(a14*a38);
  a39=(a3*a38);
  a40=(a37*a39);
  a36=(a36-a40);
  a40=(a3*a34);
  a41=(a20*a40);
  a42=(a3*a37);
  a43=(a42*a38);
  a41=(a41-a43);
  a36=(a36+a41);
  a41=cos(a5);
  a41=(a14*a41);
  a43=cos(a5);
  a43=(a14*a43);
  a44=(a3*a43);
  a45=(a41*a44);
  a46=sin(a5);
  a46=(a14*a46);
  a47=(a3*a46);
  a48=sin(a5);
  a48=(a14*a48);
  a49=(a47*a48);
  a45=(a45-a49);
  a49=(a3*a41);
  a50=(a49*a43);
  a51=(a3*a48);
  a52=(a46*a51);
  a50=(a50-a52);
  a45=(a45+a50);
  a36=(a36-a45);
  a9=(a9+a36);
  a9=(a1*a9);
  a9=(a2*a9);
  a9=(a1*a9);
  a36=arg[1]? arg[1][1] : 0;
  a45=arg[0]? arg[0][1] : 0;
  a50=cos(a45);
  a50=(a4*a50);
  a24=(a50*a24);
  a52=sin(a45);
  a52=(a4*a52);
  a35=(a52*a35);
  a24=(a24+a35);
  a35=cos(a45);
  a35=(a14*a35);
  a53=(a35*a40);
  a54=sin(a45);
  a54=(a14*a54);
  a55=(a54*a51);
  a53=(a53+a55);
  a24=(a24+a53);
  a24=(a36*a24);
  a53=sin(a45);
  a53=(a4*a53);
  a23=(a53*a23);
  a55=cos(a45);
  a55=(a4*a55);
  a28=(a55*a28);
  a23=(a23+a28);
  a28=sin(a45);
  a28=(a14*a28);
  a56=(a28*a39);
  a57=cos(a45);
  a57=(a14*a57);
  a58=(a57*a44);
  a56=(a56+a58);
  a23=(a23+a56);
  a23=(a1*a23);
  a24=(a24-a23);
  a24=(a2*a24);
  a24=(a36*a24);
  a9=(a9+a24);
  a24=arg[1]? arg[1][2] : 0;
  a23=arg[0]? arg[0][2] : 0;
  a56=cos(a23);
  a56=(a4*a56);
  a40=(a56*a40);
  a58=sin(a23);
  a58=(a4*a58);
  a51=(a58*a51);
  a40=(a40+a51);
  a40=(a24*a40);
  a51=sin(a23);
  a51=(a4*a51);
  a39=(a51*a39);
  a59=cos(a23);
  a59=(a4*a59);
  a44=(a59*a44);
  a39=(a39+a44);
  a39=(a1*a39);
  a40=(a40-a39);
  a40=(a2*a40);
  a40=(a24*a40);
  a9=(a9+a40);
  a40=-9.8000000000000007e+00;
  a8=(a3*a8);
  a8=(a40*a8);
  a39=(a3*a19);
  a39=(a40*a39);
  a8=(a8+a39);
  a39=(a3*a34);
  a39=(a40*a39);
  a8=(a8+a39);
  a9=(a9+a8);
  a8=arg[3]? arg[3][0] : 0;
  a39=cos(a5);
  a39=(a4*a39);
  a44=(a3*a39);
  a44=(a10*a44);
  a39=(a13*a39);
  a44=(a44+a39);
  a39=sin(a5);
  a39=(a4*a39);
  a60=(a3*a39);
  a60=(a12*a60);
  a39=(a18*a39);
  a60=(a60+a39);
  a44=(a44-a60);
  a60=cos(a5);
  a60=(a14*a60);
  a39=(a3*a60);
  a61=(a21*a39);
  a62=(a26*a60);
  a61=(a61+a62);
  a62=sin(a5);
  a62=(a14*a62);
  a63=(a3*a62);
  a64=(a25*a63);
  a65=(a33*a62);
  a64=(a64+a65);
  a61=(a61-a64);
  a44=(a44+a61);
  a61=cos(a5);
  a61=(a14*a61);
  a64=(a3*a61);
  a65=(a37*a64);
  a66=(a42*a61);
  a65=(a65+a66);
  a5=sin(a5);
  a5=(a14*a5);
  a66=(a3*a5);
  a67=(a41*a66);
  a68=(a49*a5);
  a67=(a67+a68);
  a65=(a65-a67);
  a44=(a44+a65);
  a65=arg[2]? arg[2][0] : 0;
  a67=arg[2]? arg[2][1] : 0;
  a65=(a65-a67);
  a7=(a10*a7);
  a13=(a13*a6);
  a7=(a7+a13);
  a12=(a12*a16);
  a18=(a18*a15);
  a12=(a12+a18);
  a7=(a7-a12);
  a12=(a21*a17);
  a18=(a26*a11);
  a12=(a12+a18);
  a18=(a25*a31);
  a15=(a33*a30);
  a18=(a18+a15);
  a12=(a12-a18);
  a7=(a7+a12);
  a12=(a37*a29);
  a18=(a42*a20);
  a12=(a12+a18);
  a18=(a41*a47);
  a15=(a49*a46);
  a18=(a18+a15);
  a12=(a12-a18);
  a7=(a7+a12);
  a12=(a7*a1);
  a12=(a2*a12);
  a18=(a12*a1);
  a15=(a53*a17);
  a16=(a55*a31);
  a15=(a15-a16);
  a16=(a28*a29);
  a13=(a57*a47);
  a16=(a16-a13);
  a15=(a15+a16);
  a16=(a15*a1);
  a13=(a26*a50);
  a6=(a33*a52);
  a13=(a13-a6);
  a6=(a42*a35);
  a68=(a49*a54);
  a6=(a6-a68);
  a13=(a13+a6);
  a6=(a13*a36);
  a16=(a16+a6);
  a16=(a2*a16);
  a6=(a16*a36);
  a18=(a18+a6);
  a6=(a51*a29);
  a68=(a59*a47);
  a6=(a6-a68);
  a68=(a6*a1);
  a69=(a42*a56);
  a70=(a49*a58);
  a69=(a69-a70);
  a70=(a69*a24);
  a68=(a68+a70);
  a68=(a2*a68);
  a70=(a68*a24);
  a18=(a18+a70);
  a10=(a3*a10);
  a10=(a40*a10);
  a70=(a3*a21);
  a70=(a40*a70);
  a10=(a10+a70);
  a70=(a3*a37);
  a70=(a40*a70);
  a10=(a10+a70);
  a18=(a18+a10);
  a18=(a18+a1);
  a65=(a65+a18);
  a18=(a8*a65);
  a10=arg[3]? arg[3][3] : 0;
  a70=arg[2]? arg[2][2] : 0;
  a67=(a67-a70);
  a71=(a3*a53);
  a72=(a71*a11);
  a73=(a3*a55);
  a74=(a73*a30);
  a72=(a72-a74);
  a74=(a3*a28);
  a75=(a74*a20);
  a76=(a3*a57);
  a77=(a76*a46);
  a75=(a75-a77);
  a72=(a72+a75);
  a75=(a72*a1);
  a77=(a3*a50);
  a78=(a21*a77);
  a79=(a3*a52);
  a80=(a25*a79);
  a78=(a78-a80);
  a80=(a3*a35);
  a81=(a37*a80);
  a82=(a3*a54);
  a83=(a41*a82);
  a81=(a81-a83);
  a78=(a78+a81);
  a81=(a78*a36);
  a75=(a75+a81);
  a75=(a2*a75);
  a81=(a75*a1);
  a83=(a53*a77);
  a84=(a71*a50);
  a83=(a83+a84);
  a84=(a55*a79);
  a85=(a73*a52);
  a84=(a84+a85);
  a83=(a83-a84);
  a84=(a28*a80);
  a85=(a74*a35);
  a84=(a84+a85);
  a85=(a57*a82);
  a86=(a76*a54);
  a85=(a85+a86);
  a84=(a84-a85);
  a83=(a83+a84);
  a84=(a83*a36);
  a84=(a2*a84);
  a85=(a84*a36);
  a81=(a81+a85);
  a85=(a51*a80);
  a86=(a59*a82);
  a85=(a85-a86);
  a86=(a85*a36);
  a87=(a74*a56);
  a88=(a76*a58);
  a87=(a87-a88);
  a88=(a87*a24);
  a86=(a86+a88);
  a86=(a2*a86);
  a88=(a86*a24);
  a81=(a81+a88);
  a88=(a3*a53);
  a88=(a40*a88);
  a89=(a3*a28);
  a89=(a40*a89);
  a88=(a88+a89);
  a81=(a81+a88);
  a81=(a81+a36);
  a67=(a67+a81);
  a81=(a10*a67);
  a18=(a18+a81);
  a81=arg[3]? arg[3][6] : 0;
  a88=(a3*a51);
  a89=(a88*a20);
  a90=(a3*a59);
  a91=(a90*a46);
  a89=(a89-a91);
  a91=(a89*a1);
  a92=(a3*a56);
  a93=(a37*a92);
  a94=(a3*a58);
  a95=(a41*a94);
  a93=(a93-a95);
  a95=(a93*a24);
  a91=(a91+a95);
  a91=(a2*a91);
  a95=(a91*a1);
  a96=(a88*a35);
  a97=(a90*a54);
  a96=(a96-a97);
  a97=(a96*a36);
  a98=(a28*a92);
  a99=(a57*a94);
  a98=(a98-a99);
  a99=(a98*a24);
  a97=(a97+a99);
  a97=(a2*a97);
  a99=(a97*a36);
  a95=(a95+a99);
  a99=(a51*a92);
  a100=(a88*a56);
  a99=(a99+a100);
  a100=(a59*a94);
  a101=(a90*a58);
  a100=(a100+a101);
  a99=(a99-a100);
  a100=(a99*a24);
  a100=(a2*a100);
  a101=(a100*a24);
  a95=(a95+a101);
  a101=(a3*a51);
  a101=(a40*a101);
  a95=(a95+a101);
  a95=(a95+a24);
  a70=(a70+a95);
  a95=(a81*a70);
  a18=(a18+a95);
  a44=(a44*a18);
  a95=(a8*a44);
  a60=(a71*a60);
  a62=(a73*a62);
  a60=(a60-a62);
  a62=(a74*a61);
  a101=(a76*a5);
  a62=(a62-a101);
  a60=(a60+a62);
  a60=(a60*a18);
  a62=cos(a45);
  a62=(a4*a62);
  a101=(a3*a62);
  a102=(a21*a101);
  a103=sin(a45);
  a103=(a4*a103);
  a104=(a3*a103);
  a105=(a25*a104);
  a102=(a102-a105);
  a105=cos(a45);
  a105=(a14*a105);
  a106=(a3*a105);
  a107=(a37*a106);
  a108=sin(a45);
  a108=(a14*a108);
  a109=(a3*a108);
  a110=(a41*a109);
  a107=(a107-a110);
  a102=(a102+a107);
  a107=arg[3]? arg[3][1] : 0;
  a110=(a107*a65);
  a111=arg[3]? arg[3][4] : 0;
  a112=(a111*a67);
  a110=(a110+a112);
  a112=arg[3]? arg[3][7] : 0;
  a113=(a112*a70);
  a110=(a110+a113);
  a102=(a102*a110);
  a60=(a60+a102);
  a102=(a10*a60);
  a95=(a95+a102);
  a61=(a88*a61);
  a5=(a90*a5);
  a61=(a61-a5);
  a61=(a61*a18);
  a5=cos(a23);
  a5=(a4*a5);
  a102=(a3*a5);
  a113=(a37*a102);
  a114=sin(a23);
  a114=(a4*a114);
  a115=(a3*a114);
  a116=(a41*a115);
  a113=(a113-a116);
  a116=arg[3]? arg[3][2] : 0;
  a65=(a116*a65);
  a117=arg[3]? arg[3][5] : 0;
  a67=(a117*a67);
  a65=(a65+a67);
  a67=arg[3]? arg[3][8] : 0;
  a70=(a67*a70);
  a65=(a65+a70);
  a113=(a113*a65);
  a61=(a61+a113);
  a113=(a81*a61);
  a95=(a95+a113);
  a9=(a9-a95);
  if (res[0]!=0) res[0][3]=a9;
  a19=(a77*a19);
  a32=(a79*a32);
  a19=(a19+a32);
  a32=(a80*a34);
  a9=(a82*a48);
  a32=(a32+a9);
  a19=(a19+a32);
  a19=(a36*a19);
  a22=(a71*a22);
  a27=(a73*a27);
  a22=(a22+a27);
  a27=(a74*a38);
  a32=(a76*a43);
  a27=(a27+a32);
  a22=(a22+a27);
  a22=(a1*a22);
  a19=(a19-a22);
  a19=(a2*a19);
  a19=(a1*a19);
  a22=(a107*a44);
  a27=(a111*a60);
  a22=(a22+a27);
  a27=(a112*a61);
  a22=(a22+a27);
  a19=(a19-a22);
  if (res[0]!=0) res[0][4]=a19;
  a34=(a92*a34);
  a48=(a94*a48);
  a34=(a34+a48);
  a34=(a24*a34);
  a38=(a88*a38);
  a43=(a90*a43);
  a38=(a38+a43);
  a38=(a1*a38);
  a34=(a34-a38);
  a34=(a2*a34);
  a34=(a1*a34);
  a44=(a116*a44);
  a60=(a117*a60);
  a44=(a44+a60);
  a61=(a67*a61);
  a44=(a44+a61);
  a34=(a34-a44);
  if (res[0]!=0) res[0][5]=a34;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  a34=cos(a45);
  a34=(a4*a34);
  a17=(a17*a34);
  a44=sin(a45);
  a44=(a4*a44);
  a31=(a31*a44);
  a17=(a17+a31);
  a31=cos(a45);
  a31=(a14*a31);
  a61=(a29*a31);
  a60=sin(a45);
  a60=(a14*a60);
  a38=(a47*a60);
  a61=(a61+a38);
  a17=(a17+a61);
  a17=(a1*a17);
  a61=sin(a45);
  a61=(a4*a61);
  a38=(a26*a61);
  a43=cos(a45);
  a43=(a4*a43);
  a48=(a33*a43);
  a38=(a38+a48);
  a48=sin(a45);
  a48=(a14*a48);
  a19=(a42*a48);
  a45=cos(a45);
  a14=(a14*a45);
  a45=(a49*a14);
  a19=(a19+a45);
  a38=(a38+a19);
  a38=(a36*a38);
  a17=(a17-a38);
  a17=(a2*a17);
  a17=(a36*a17);
  a39=(a53*a39);
  a63=(a55*a63);
  a39=(a39-a63);
  a63=(a28*a64);
  a38=(a57*a66);
  a63=(a63-a38);
  a39=(a39+a63);
  a39=(a39*a18);
  a26=(a26*a62);
  a33=(a33*a103);
  a26=(a26-a33);
  a33=(a42*a105);
  a63=(a49*a108);
  a33=(a33-a63);
  a26=(a26+a33);
  a26=(a26*a110);
  a39=(a39+a26);
  a26=(a8*a39);
  a101=(a53*a101);
  a62=(a71*a62);
  a101=(a101+a62);
  a104=(a55*a104);
  a103=(a73*a103);
  a104=(a104+a103);
  a101=(a101-a104);
  a104=(a28*a106);
  a103=(a74*a105);
  a104=(a104+a103);
  a103=(a57*a109);
  a62=(a76*a108);
  a103=(a103+a62);
  a104=(a104-a103);
  a101=(a101+a104);
  a101=(a101*a110);
  a104=(a10*a101);
  a26=(a26+a104);
  a105=(a88*a105);
  a108=(a90*a108);
  a105=(a105-a108);
  a105=(a105*a110);
  a108=(a28*a102);
  a104=(a57*a115);
  a108=(a108-a104);
  a108=(a108*a65);
  a105=(a105+a108);
  a108=(a81*a105);
  a26=(a26+a108);
  a17=(a17-a26);
  if (res[0]!=0) res[0][9]=a17;
  a17=(a3*a34);
  a11=(a11*a17);
  a26=(a3*a44);
  a30=(a30*a26);
  a11=(a11+a30);
  a30=(a3*a31);
  a108=(a20*a30);
  a104=(a3*a60);
  a103=(a46*a104);
  a108=(a108+a103);
  a11=(a11+a108);
  a11=(a1*a11);
  a108=(a3*a61);
  a21=(a21*a108);
  a103=(a3*a43);
  a25=(a25*a103);
  a21=(a21+a25);
  a25=(a3*a48);
  a62=(a37*a25);
  a33=(a3*a14);
  a63=(a41*a33);
  a62=(a62+a63);
  a21=(a21+a62);
  a21=(a36*a21);
  a11=(a11-a21);
  a11=(a2*a11);
  a11=(a1*a11);
  a77=(a77*a34);
  a53=(a53*a108);
  a77=(a77-a53);
  a50=(a50*a17);
  a71=(a71*a61);
  a50=(a50-a71);
  a77=(a77+a50);
  a55=(a55*a103);
  a79=(a79*a44);
  a55=(a55-a79);
  a73=(a73*a43);
  a52=(a52*a26);
  a73=(a73-a52);
  a55=(a55+a73);
  a77=(a77-a55);
  a55=(a80*a31);
  a73=(a28*a25);
  a55=(a55-a73);
  a73=(a35*a30);
  a52=(a74*a48);
  a73=(a73-a52);
  a55=(a55+a73);
  a73=(a57*a33);
  a52=(a82*a60);
  a73=(a73-a52);
  a52=(a76*a14);
  a26=(a54*a104);
  a52=(a52-a26);
  a73=(a73+a52);
  a55=(a55-a73);
  a77=(a77+a55);
  a77=(a36*a77);
  a77=(a2*a77);
  a77=(a36*a77);
  a11=(a11+a77);
  a30=(a56*a30);
  a104=(a58*a104);
  a30=(a30+a104);
  a30=(a24*a30);
  a25=(a51*a25);
  a33=(a59*a33);
  a25=(a25+a33);
  a25=(a36*a25);
  a30=(a30-a25);
  a30=(a2*a30);
  a30=(a24*a30);
  a11=(a11+a30);
  a34=(a3*a34);
  a34=(a40*a34);
  a30=(a3*a31);
  a30=(a40*a30);
  a34=(a34+a30);
  a11=(a11+a34);
  a34=(a107*a39);
  a30=(a111*a101);
  a34=(a34+a30);
  a30=(a112*a105);
  a34=(a34+a30);
  a11=(a11-a34);
  if (res[0]!=0) res[0][10]=a11;
  a31=(a92*a31);
  a60=(a94*a60);
  a31=(a31+a60);
  a31=(a24*a31);
  a48=(a88*a48);
  a14=(a90*a14);
  a48=(a48+a14);
  a48=(a36*a48);
  a31=(a31-a48);
  a31=(a2*a31);
  a31=(a36*a31);
  a39=(a116*a39);
  a101=(a117*a101);
  a39=(a39+a101);
  a105=(a67*a105);
  a39=(a39+a105);
  a31=(a31-a39);
  if (res[0]!=0) res[0][11]=a31;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a31=cos(a23);
  a31=(a4*a31);
  a29=(a29*a31);
  a39=sin(a23);
  a39=(a4*a39);
  a47=(a47*a39);
  a29=(a29+a47);
  a29=(a1*a29);
  a47=sin(a23);
  a47=(a4*a47);
  a105=(a42*a47);
  a23=cos(a23);
  a4=(a4*a23);
  a23=(a49*a4);
  a105=(a105+a23);
  a105=(a24*a105);
  a29=(a29-a105);
  a29=(a2*a29);
  a29=(a24*a29);
  a64=(a51*a64);
  a66=(a59*a66);
  a64=(a64-a66);
  a64=(a64*a18);
  a42=(a42*a5);
  a49=(a49*a114);
  a42=(a42-a49);
  a42=(a42*a65);
  a64=(a64+a42);
  a42=(a8*a64);
  a106=(a51*a106);
  a109=(a59*a109);
  a106=(a106-a109);
  a106=(a106*a110);
  a110=(a74*a5);
  a109=(a76*a114);
  a110=(a110-a109);
  a110=(a110*a65);
  a106=(a106+a110);
  a110=(a10*a106);
  a42=(a42+a110);
  a102=(a51*a102);
  a5=(a88*a5);
  a102=(a102+a5);
  a115=(a59*a115);
  a114=(a90*a114);
  a115=(a115+a114);
  a102=(a102-a115);
  a102=(a102*a65);
  a65=(a81*a102);
  a42=(a42+a65);
  a29=(a29-a42);
  if (res[0]!=0) res[0][15]=a29;
  a80=(a80*a31);
  a82=(a82*a39);
  a80=(a80+a82);
  a80=(a36*a80);
  a74=(a74*a47);
  a76=(a76*a4);
  a74=(a74+a76);
  a74=(a24*a74);
  a80=(a80-a74);
  a80=(a2*a80);
  a80=(a24*a80);
  a74=(a107*a64);
  a76=(a111*a106);
  a74=(a74+a76);
  a76=(a112*a102);
  a74=(a74+a76);
  a80=(a80-a74);
  if (res[0]!=0) res[0][16]=a80;
  a80=(a3*a31);
  a20=(a20*a80);
  a74=(a3*a39);
  a46=(a46*a74);
  a20=(a20+a46);
  a20=(a1*a20);
  a46=(a3*a47);
  a37=(a37*a46);
  a76=(a3*a4);
  a41=(a41*a76);
  a37=(a37+a41);
  a37=(a24*a37);
  a20=(a20-a37);
  a20=(a2*a20);
  a20=(a1*a20);
  a35=(a35*a80);
  a54=(a54*a74);
  a35=(a35+a54);
  a35=(a36*a35);
  a28=(a28*a46);
  a57=(a57*a76);
  a28=(a28+a57);
  a28=(a24*a28);
  a35=(a35-a28);
  a35=(a2*a35);
  a35=(a36*a35);
  a20=(a20+a35);
  a92=(a92*a31);
  a51=(a51*a46);
  a92=(a92-a51);
  a56=(a56*a80);
  a88=(a88*a47);
  a56=(a56-a88);
  a92=(a92+a56);
  a59=(a59*a76);
  a94=(a94*a39);
  a59=(a59-a94);
  a90=(a90*a4);
  a58=(a58*a74);
  a90=(a90-a58);
  a59=(a59+a90);
  a92=(a92-a59);
  a92=(a24*a92);
  a92=(a2*a92);
  a92=(a24*a92);
  a20=(a20+a92);
  a3=(a3*a31);
  a40=(a40*a3);
  a20=(a20+a40);
  a64=(a116*a64);
  a106=(a117*a106);
  a64=(a64+a106);
  a102=(a67*a102);
  a64=(a64+a102);
  a20=(a20-a64);
  if (res[0]!=0) res[0][17]=a20;
  a20=1.;
  if (res[0]!=0) res[0][18]=a20;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(a7+a12);
  a15=(a2*a15);
  a15=(a36*a15);
  a7=(a7+a15);
  a6=(a2*a6);
  a6=(a24*a6);
  a7=(a7+a6);
  a7=(a7+a20);
  a6=(a8*a7);
  a72=(a2*a72);
  a72=(a1*a72);
  a72=(a72+a75);
  a75=(a10*a72);
  a6=(a6+a75);
  a89=(a2*a89);
  a89=(a1*a89);
  a89=(a89+a91);
  a91=(a81*a89);
  a6=(a6+a91);
  if (res[0]!=0) res[0][21]=a6;
  a6=(a107*a7);
  a91=(a111*a72);
  a6=(a6+a91);
  a91=(a112*a89);
  a6=(a6+a91);
  if (res[0]!=0) res[0][22]=a6;
  a7=(a116*a7);
  a72=(a117*a72);
  a7=(a7+a72);
  a89=(a67*a89);
  a7=(a7+a89);
  if (res[0]!=0) res[0][23]=a7;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a20;
  if (res[0]!=0) res[0][26]=a0;
  a13=(a2*a13);
  a13=(a36*a13);
  a13=(a13+a16);
  a16=(a8*a13);
  a78=(a2*a78);
  a78=(a1*a78);
  a83=(a2*a83);
  a83=(a36*a83);
  a83=(a83+a84);
  a78=(a78+a83);
  a85=(a2*a85);
  a85=(a24*a85);
  a78=(a78+a85);
  a78=(a78+a20);
  a85=(a10*a78);
  a16=(a16+a85);
  a96=(a2*a96);
  a96=(a36*a96);
  a96=(a96+a97);
  a97=(a81*a96);
  a16=(a16+a97);
  if (res[0]!=0) res[0][27]=a16;
  a16=(a107*a13);
  a97=(a111*a78);
  a16=(a16+a97);
  a97=(a112*a96);
  a16=(a16+a97);
  if (res[0]!=0) res[0][28]=a16;
  a13=(a116*a13);
  a78=(a117*a78);
  a13=(a13+a78);
  a96=(a67*a96);
  a13=(a13+a96);
  if (res[0]!=0) res[0][29]=a13;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a20;
  a69=(a2*a69);
  a69=(a24*a69);
  a69=(a69+a68);
  a8=(a8*a69);
  a87=(a2*a87);
  a87=(a24*a87);
  a87=(a87+a86);
  a10=(a10*a87);
  a8=(a8+a10);
  a93=(a2*a93);
  a1=(a1*a93);
  a98=(a2*a98);
  a36=(a36*a98);
  a1=(a1+a36);
  a2=(a2*a99);
  a24=(a24*a2);
  a24=(a24+a100);
  a1=(a1+a24);
  a1=(a1+a20);
  a81=(a81*a1);
  a8=(a8+a81);
  if (res[0]!=0) res[0][33]=a8;
  a107=(a107*a69);
  a111=(a111*a87);
  a107=(a107+a111);
  a112=(a112*a1);
  a107=(a107+a112);
  if (res[0]!=0) res[0][34]=a107;
  a116=(a116*a69);
  a117=(a117*a87);
  a116=(a116+a117);
  a67=(a67*a1);
  a116=(a116+a67);
  if (res[0]!=0) res[0][35]=a116;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_A(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_A_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_A_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_A_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_A_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_A_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_A_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_A_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_A_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_A_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_A_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_A_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "u";
    case 3: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_A_name_out(casadi_int i){
  switch (i) {
    case 0: return "A";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_A_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_A_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_A_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_linearization_B:(q[3],v[3],iH[3x3])->(B[6x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a1=arg[2]? arg[2][0] : 0;
  if (res[0]!=0) res[0][3]=a1;
  a2=arg[2]? arg[2][1] : 0;
  if (res[0]!=0) res[0][4]=a2;
  a3=arg[2]? arg[2][2] : 0;
  if (res[0]!=0) res[0][5]=a3;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  a4=arg[2]? arg[2][3] : 0;
  a1=(a4-a1);
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[2]? arg[2][4] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][10]=a2;
  a2=arg[2]? arg[2][5] : 0;
  a3=(a2-a3);
  if (res[0]!=0) res[0][11]=a3;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[2]? arg[2][6] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[2]? arg[2][7] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[2]? arg[2][8] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][17]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_B(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_B_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_B_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_B_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_B_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_B_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_B_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_B_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_B_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_B_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_B_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_B_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_B_name_out(casadi_int i){
  switch (i) {
    case 0: return "B";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_B_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_B_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_B_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_linearization_c:(q[3],v[3],u[3],iH[3x3])->(c[6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=5.0000000000000000e-01;
  a2=2.9999999999999999e-01;
  a3=arg[0]? arg[0][0] : 0;
  a4=sin(a3);
  a4=(a2*a4);
  a5=20.;
  a6=cos(a3);
  a6=(a2*a6);
  a7=(a5*a6);
  a8=(a4*a7);
  a9=(a5*a4);
  a10=(a9*a6);
  a8=(a8+a10);
  a10=cos(a3);
  a10=(a2*a10);
  a11=sin(a3);
  a11=(a2*a11);
  a12=(a5*a11);
  a13=(a10*a12);
  a14=(a5*a10);
  a15=(a14*a11);
  a13=(a13+a15);
  a8=(a8-a13);
  a13=5.9999999999999998e-01;
  a15=sin(a3);
  a15=(a13*a15);
  a16=cos(a3);
  a16=(a13*a16);
  a17=(a5*a16);
  a18=(a15*a17);
  a19=(a5*a15);
  a20=(a19*a16);
  a18=(a18+a20);
  a20=cos(a3);
  a20=(a13*a20);
  a21=sin(a3);
  a21=(a13*a21);
  a22=(a5*a21);
  a23=(a20*a22);
  a24=(a5*a20);
  a25=(a24*a21);
  a23=(a23+a25);
  a18=(a18-a23);
  a8=(a8+a18);
  a18=sin(a3);
  a18=(a13*a18);
  a23=cos(a3);
  a23=(a13*a23);
  a25=(a5*a23);
  a26=(a18*a25);
  a27=(a5*a18);
  a28=(a27*a23);
  a26=(a26+a28);
  a28=cos(a3);
  a28=(a13*a28);
  a29=sin(a3);
  a29=(a13*a29);
  a30=(a5*a29);
  a31=(a28*a30);
  a32=(a5*a28);
  a33=(a32*a29);
  a31=(a31+a33);
  a26=(a26-a31);
  a8=(a8+a26);
  a26=arg[1]? arg[1][0] : 0;
  a31=(a8*a26);
  a31=(a1*a31);
  a33=(a31*a26);
  a34=arg[0]? arg[0][1] : 0;
  a35=sin(a34);
  a35=(a2*a35);
  a36=(a35*a17);
  a37=cos(a34);
  a37=(a2*a37);
  a38=(a37*a22);
  a36=(a36-a38);
  a38=sin(a34);
  a38=(a13*a38);
  a39=(a38*a25);
  a40=cos(a34);
  a40=(a13*a40);
  a41=(a40*a30);
  a39=(a39-a41);
  a36=(a36+a39);
  a39=(a36*a26);
  a41=cos(a34);
  a41=(a2*a41);
  a42=(a19*a41);
  a43=sin(a34);
  a43=(a2*a43);
  a44=(a24*a43);
  a42=(a42-a44);
  a44=cos(a34);
  a44=(a13*a44);
  a45=(a27*a44);
  a46=sin(a34);
  a46=(a13*a46);
  a47=(a32*a46);
  a45=(a45-a47);
  a42=(a42+a45);
  a45=arg[1]? arg[1][1] : 0;
  a47=(a42*a45);
  a39=(a39+a47);
  a39=(a1*a39);
  a47=(a39*a45);
  a33=(a33+a47);
  a47=arg[0]? arg[0][2] : 0;
  a48=sin(a47);
  a48=(a2*a48);
  a49=(a48*a25);
  a50=cos(a47);
  a50=(a2*a50);
  a51=(a50*a30);
  a49=(a49-a51);
  a51=(a49*a26);
  a52=cos(a47);
  a52=(a2*a52);
  a53=(a27*a52);
  a54=sin(a47);
  a54=(a2*a54);
  a55=(a32*a54);
  a53=(a53-a55);
  a55=arg[1]? arg[1][2] : 0;
  a56=(a53*a55);
  a51=(a51+a56);
  a51=(a1*a51);
  a56=(a51*a55);
  a33=(a33+a56);
  a56=-9.8000000000000007e+00;
  a57=(a5*a4);
  a57=(a56*a57);
  a58=(a5*a15);
  a58=(a56*a58);
  a57=(a57+a58);
  a58=(a5*a18);
  a58=(a56*a58);
  a57=(a57+a58);
  a33=(a33+a57);
  a33=(a33+a26);
  a57=(a0*a33);
  a58=arg[3]? arg[3][3] : 0;
  a59=(a5*a35);
  a60=(a59*a16);
  a61=(a5*a37);
  a62=(a61*a21);
  a60=(a60-a62);
  a62=(a5*a38);
  a63=(a62*a23);
  a64=(a5*a40);
  a65=(a64*a29);
  a63=(a63-a65);
  a60=(a60+a63);
  a63=(a60*a26);
  a65=(a5*a41);
  a66=(a15*a65);
  a67=(a5*a43);
  a68=(a20*a67);
  a66=(a66-a68);
  a68=(a5*a44);
  a69=(a18*a68);
  a70=(a5*a46);
  a71=(a28*a70);
  a69=(a69-a71);
  a66=(a66+a69);
  a69=(a66*a45);
  a63=(a63+a69);
  a63=(a1*a63);
  a69=(a63*a26);
  a71=(a35*a65);
  a72=(a59*a41);
  a71=(a71+a72);
  a72=(a37*a67);
  a73=(a61*a43);
  a72=(a72+a73);
  a71=(a71-a72);
  a72=(a38*a68);
  a73=(a62*a44);
  a72=(a72+a73);
  a73=(a40*a70);
  a74=(a64*a46);
  a73=(a73+a74);
  a72=(a72-a73);
  a71=(a71+a72);
  a72=(a71*a45);
  a72=(a1*a72);
  a73=(a72*a45);
  a69=(a69+a73);
  a73=(a48*a68);
  a74=(a50*a70);
  a73=(a73-a74);
  a74=(a73*a45);
  a75=(a62*a52);
  a76=(a64*a54);
  a75=(a75-a76);
  a76=(a75*a55);
  a74=(a74+a76);
  a74=(a1*a74);
  a76=(a74*a55);
  a69=(a69+a76);
  a76=(a5*a35);
  a76=(a56*a76);
  a77=(a5*a38);
  a77=(a56*a77);
  a76=(a76+a77);
  a69=(a69+a76);
  a69=(a69+a45);
  a76=(a58*a69);
  a57=(a57+a76);
  a76=arg[3]? arg[3][6] : 0;
  a77=(a5*a48);
  a78=(a77*a23);
  a79=(a5*a50);
  a80=(a79*a29);
  a78=(a78-a80);
  a80=(a78*a26);
  a81=(a5*a52);
  a82=(a18*a81);
  a83=(a5*a54);
  a84=(a28*a83);
  a82=(a82-a84);
  a84=(a82*a55);
  a80=(a80+a84);
  a80=(a1*a80);
  a84=(a80*a26);
  a85=(a77*a44);
  a86=(a79*a46);
  a85=(a85-a86);
  a86=(a85*a45);
  a87=(a38*a81);
  a88=(a40*a83);
  a87=(a87-a88);
  a88=(a87*a55);
  a86=(a86+a88);
  a86=(a1*a86);
  a88=(a86*a45);
  a84=(a84+a88);
  a88=(a48*a81);
  a89=(a77*a52);
  a88=(a88+a89);
  a89=(a50*a83);
  a90=(a79*a54);
  a89=(a89+a90);
  a88=(a88-a89);
  a89=(a88*a55);
  a89=(a1*a89);
  a90=(a89*a55);
  a84=(a84+a90);
  a90=(a5*a48);
  a90=(a56*a90);
  a84=(a84+a90);
  a84=(a84+a55);
  a90=(a76*a84);
  a57=(a57+a90);
  a90=cos(a3);
  a90=(a2*a90);
  a7=(a7*a90);
  a91=sin(a3);
  a91=(a2*a91);
  a92=(a5*a91);
  a92=(a4*a92);
  a7=(a7-a92);
  a92=(a5*a90);
  a6=(a6*a92);
  a91=(a9*a91);
  a6=(a6-a91);
  a7=(a7+a6);
  a6=cos(a3);
  a6=(a2*a6);
  a91=(a5*a6);
  a91=(a10*a91);
  a92=sin(a3);
  a92=(a2*a92);
  a12=(a12*a92);
  a91=(a91-a12);
  a6=(a14*a6);
  a92=(a5*a92);
  a11=(a11*a92);
  a6=(a6-a11);
  a91=(a91+a6);
  a7=(a7-a91);
  a91=cos(a3);
  a91=(a13*a91);
  a6=(a17*a91);
  a11=sin(a3);
  a11=(a13*a11);
  a92=(a5*a11);
  a12=(a15*a92);
  a6=(a6-a12);
  a12=(a5*a91);
  a93=(a16*a12);
  a94=(a19*a11);
  a93=(a93-a94);
  a6=(a6+a93);
  a93=cos(a3);
  a93=(a13*a93);
  a94=(a5*a93);
  a95=(a20*a94);
  a96=sin(a3);
  a96=(a13*a96);
  a97=(a22*a96);
  a95=(a95-a97);
  a97=(a24*a93);
  a98=(a5*a96);
  a99=(a21*a98);
  a97=(a97-a99);
  a95=(a95+a97);
  a6=(a6-a95);
  a7=(a7+a6);
  a6=cos(a3);
  a6=(a13*a6);
  a95=(a25*a6);
  a97=sin(a3);
  a97=(a13*a97);
  a99=(a5*a97);
  a100=(a18*a99);
  a95=(a95-a100);
  a100=(a5*a6);
  a101=(a23*a100);
  a102=(a27*a97);
  a101=(a101-a102);
  a95=(a95+a101);
  a101=cos(a3);
  a101=(a13*a101);
  a102=(a5*a101);
  a103=(a28*a102);
  a104=sin(a3);
  a104=(a13*a104);
  a105=(a30*a104);
  a103=(a103-a105);
  a105=(a32*a101);
  a106=(a5*a104);
  a107=(a29*a106);
  a105=(a105-a107);
  a103=(a103+a105);
  a95=(a95-a103);
  a7=(a7+a95);
  a7=(a26*a7);
  a7=(a1*a7);
  a7=(a26*a7);
  a12=(a41*a12);
  a98=(a43*a98);
  a12=(a12+a98);
  a98=(a44*a100);
  a95=(a46*a106);
  a98=(a98+a95);
  a12=(a12+a98);
  a12=(a45*a12);
  a92=(a35*a92);
  a94=(a37*a94);
  a92=(a92+a94);
  a94=(a38*a99);
  a98=(a40*a102);
  a94=(a94+a98);
  a92=(a92+a94);
  a92=(a26*a92);
  a12=(a12-a92);
  a12=(a1*a12);
  a12=(a45*a12);
  a7=(a7+a12);
  a100=(a52*a100);
  a106=(a54*a106);
  a100=(a100+a106);
  a100=(a55*a100);
  a99=(a48*a99);
  a102=(a50*a102);
  a99=(a99+a102);
  a99=(a26*a99);
  a100=(a100-a99);
  a100=(a1*a100);
  a100=(a55*a100);
  a7=(a7+a100);
  a90=(a5*a90);
  a90=(a56*a90);
  a100=(a5*a91);
  a100=(a56*a100);
  a90=(a90+a100);
  a100=(a5*a6);
  a100=(a56*a100);
  a90=(a90+a100);
  a7=(a7+a90);
  a90=cos(a3);
  a90=(a2*a90);
  a100=(a5*a90);
  a4=(a4*a100);
  a9=(a9*a90);
  a4=(a4+a9);
  a9=sin(a3);
  a9=(a2*a9);
  a90=(a5*a9);
  a10=(a10*a90);
  a14=(a14*a9);
  a10=(a10+a14);
  a4=(a4-a10);
  a10=cos(a3);
  a10=(a13*a10);
  a14=(a5*a10);
  a9=(a15*a14);
  a90=(a19*a10);
  a9=(a9+a90);
  a90=sin(a3);
  a90=(a13*a90);
  a100=(a5*a90);
  a99=(a20*a100);
  a102=(a24*a90);
  a99=(a99+a102);
  a9=(a9-a99);
  a4=(a4+a9);
  a9=cos(a3);
  a9=(a13*a9);
  a99=(a5*a9);
  a102=(a18*a99);
  a106=(a27*a9);
  a102=(a102+a106);
  a106=sin(a3);
  a106=(a13*a106);
  a12=(a5*a106);
  a92=(a28*a12);
  a94=(a32*a106);
  a92=(a92+a94);
  a102=(a102-a92);
  a4=(a4+a102);
  a102=arg[2]? arg[2][0] : 0;
  a92=arg[2]? arg[2][1] : 0;
  a102=(a102-a92);
  a102=(a102+a33);
  a94=(a0*a102);
  a98=arg[2]? arg[2][2] : 0;
  a92=(a92-a98);
  a92=(a92+a69);
  a95=(a58*a92);
  a94=(a94+a95);
  a98=(a98+a84);
  a95=(a76*a98);
  a94=(a94+a95);
  a4=(a4*a94);
  a95=(a0*a4);
  a10=(a59*a10);
  a90=(a61*a90);
  a10=(a10-a90);
  a90=(a62*a9);
  a103=(a64*a106);
  a90=(a90-a103);
  a10=(a10+a90);
  a10=(a10*a94);
  a90=cos(a34);
  a90=(a2*a90);
  a103=(a5*a90);
  a105=(a15*a103);
  a107=sin(a34);
  a107=(a2*a107);
  a108=(a5*a107);
  a109=(a20*a108);
  a105=(a105-a109);
  a109=cos(a34);
  a109=(a13*a109);
  a110=(a5*a109);
  a111=(a18*a110);
  a112=sin(a34);
  a112=(a13*a112);
  a113=(a5*a112);
  a114=(a28*a113);
  a111=(a111-a114);
  a105=(a105+a111);
  a111=arg[3]? arg[3][1] : 0;
  a114=(a111*a102);
  a115=arg[3]? arg[3][4] : 0;
  a116=(a115*a92);
  a114=(a114+a116);
  a116=arg[3]? arg[3][7] : 0;
  a117=(a116*a98);
  a114=(a114+a117);
  a105=(a105*a114);
  a10=(a10+a105);
  a105=(a58*a10);
  a95=(a95+a105);
  a9=(a77*a9);
  a106=(a79*a106);
  a9=(a9-a106);
  a9=(a9*a94);
  a106=cos(a47);
  a106=(a2*a106);
  a105=(a5*a106);
  a117=(a18*a105);
  a118=sin(a47);
  a118=(a2*a118);
  a119=(a5*a118);
  a120=(a28*a119);
  a117=(a117-a120);
  a120=arg[3]? arg[3][2] : 0;
  a102=(a120*a102);
  a121=arg[3]? arg[3][5] : 0;
  a92=(a121*a92);
  a102=(a102+a92);
  a92=arg[3]? arg[3][8] : 0;
  a98=(a92*a98);
  a102=(a102+a98);
  a117=(a117*a102);
  a9=(a9+a117);
  a117=(a76*a9);
  a95=(a95+a117);
  a7=(a7-a95);
  a7=(a7*a3);
  a95=cos(a34);
  a95=(a2*a95);
  a17=(a17*a95);
  a117=sin(a34);
  a117=(a2*a117);
  a22=(a22*a117);
  a17=(a17+a22);
  a22=cos(a34);
  a22=(a13*a22);
  a98=(a25*a22);
  a122=sin(a34);
  a122=(a13*a122);
  a123=(a30*a122);
  a98=(a98+a123);
  a17=(a17+a98);
  a17=(a26*a17);
  a98=sin(a34);
  a98=(a2*a98);
  a123=(a19*a98);
  a124=cos(a34);
  a124=(a2*a124);
  a125=(a24*a124);
  a123=(a123+a125);
  a125=sin(a34);
  a125=(a13*a125);
  a126=(a27*a125);
  a127=cos(a34);
  a13=(a13*a127);
  a127=(a32*a13);
  a126=(a126+a127);
  a123=(a123+a126);
  a123=(a45*a123);
  a17=(a17-a123);
  a17=(a1*a17);
  a17=(a45*a17);
  a14=(a35*a14);
  a100=(a37*a100);
  a14=(a14-a100);
  a100=(a38*a99);
  a123=(a40*a12);
  a100=(a100-a123);
  a14=(a14+a100);
  a14=(a14*a94);
  a19=(a19*a90);
  a24=(a24*a107);
  a19=(a19-a24);
  a24=(a27*a109);
  a100=(a32*a112);
  a24=(a24-a100);
  a19=(a19+a24);
  a19=(a19*a114);
  a14=(a14+a19);
  a19=(a0*a14);
  a103=(a35*a103);
  a90=(a59*a90);
  a103=(a103+a90);
  a108=(a37*a108);
  a107=(a61*a107);
  a108=(a108+a107);
  a103=(a103-a108);
  a108=(a38*a110);
  a107=(a62*a109);
  a108=(a108+a107);
  a107=(a40*a113);
  a90=(a64*a112);
  a107=(a107+a90);
  a108=(a108-a107);
  a103=(a103+a108);
  a103=(a103*a114);
  a108=(a58*a103);
  a19=(a19+a108);
  a109=(a77*a109);
  a112=(a79*a112);
  a109=(a109-a112);
  a109=(a109*a114);
  a112=(a38*a105);
  a108=(a40*a119);
  a112=(a112-a108);
  a112=(a112*a102);
  a109=(a109+a112);
  a112=(a76*a109);
  a19=(a19+a112);
  a17=(a17-a19);
  a17=(a17*a34);
  a7=(a7+a17);
  a17=cos(a47);
  a17=(a2*a17);
  a25=(a25*a17);
  a19=sin(a47);
  a19=(a2*a19);
  a30=(a30*a19);
  a25=(a25+a30);
  a25=(a26*a25);
  a30=sin(a47);
  a30=(a2*a30);
  a112=(a27*a30);
  a108=cos(a47);
  a2=(a2*a108);
  a108=(a32*a2);
  a112=(a112+a108);
  a112=(a55*a112);
  a25=(a25-a112);
  a25=(a1*a25);
  a25=(a55*a25);
  a99=(a48*a99);
  a12=(a50*a12);
  a99=(a99-a12);
  a99=(a99*a94);
  a27=(a27*a106);
  a32=(a32*a118);
  a27=(a27-a32);
  a27=(a27*a102);
  a99=(a99+a27);
  a27=(a0*a99);
  a110=(a48*a110);
  a113=(a50*a113);
  a110=(a110-a113);
  a110=(a110*a114);
  a114=(a62*a106);
  a113=(a64*a118);
  a114=(a114-a113);
  a114=(a114*a102);
  a110=(a110+a114);
  a114=(a58*a110);
  a27=(a27+a114);
  a105=(a48*a105);
  a106=(a77*a106);
  a105=(a105+a106);
  a119=(a50*a119);
  a118=(a79*a118);
  a119=(a119+a118);
  a105=(a105-a119);
  a105=(a105*a102);
  a102=(a76*a105);
  a27=(a27+a102);
  a25=(a25-a27);
  a25=(a25*a47);
  a7=(a7+a25);
  a57=(a57-a7);
  a8=(a1*a8);
  a8=(a26*a8);
  a8=(a8+a31);
  a36=(a1*a36);
  a36=(a45*a36);
  a8=(a8+a36);
  a49=(a1*a49);
  a49=(a55*a49);
  a8=(a8+a49);
  a49=1.;
  a8=(a8+a49);
  a36=(a0*a8);
  a60=(a1*a60);
  a60=(a26*a60);
  a60=(a60+a63);
  a63=(a58*a60);
  a36=(a36+a63);
  a78=(a1*a78);
  a78=(a26*a78);
  a78=(a78+a80);
  a80=(a76*a78);
  a36=(a36+a80);
  a36=(a36*a26);
  a42=(a1*a42);
  a42=(a45*a42);
  a42=(a42+a39);
  a39=(a0*a42);
  a66=(a1*a66);
  a66=(a26*a66);
  a71=(a1*a71);
  a71=(a45*a71);
  a71=(a71+a72);
  a66=(a66+a71);
  a73=(a1*a73);
  a73=(a55*a73);
  a66=(a66+a73);
  a66=(a66+a49);
  a73=(a58*a66);
  a39=(a39+a73);
  a85=(a1*a85);
  a85=(a45*a85);
  a85=(a85+a86);
  a86=(a76*a85);
  a39=(a39+a86);
  a39=(a39*a45);
  a36=(a36+a39);
  a53=(a1*a53);
  a53=(a55*a53);
  a53=(a53+a51);
  a0=(a0*a53);
  a75=(a1*a75);
  a75=(a55*a75);
  a75=(a75+a74);
  a58=(a58*a75);
  a0=(a0+a58);
  a82=(a1*a82);
  a82=(a26*a82);
  a87=(a1*a87);
  a87=(a45*a87);
  a82=(a82+a87);
  a88=(a1*a88);
  a88=(a55*a88);
  a88=(a88+a89);
  a82=(a82+a88);
  a82=(a82+a49);
  a76=(a76*a82);
  a0=(a0+a76);
  a0=(a0*a55);
  a36=(a36+a0);
  a57=(a57-a36);
  if (res[0]!=0) res[0][3]=a57;
  a57=(a111*a33);
  a36=(a115*a69);
  a57=(a57+a36);
  a36=(a116*a84);
  a57=(a57+a36);
  a91=(a65*a91);
  a96=(a67*a96);
  a91=(a91+a96);
  a96=(a68*a6);
  a36=(a70*a104);
  a96=(a96+a36);
  a91=(a91+a96);
  a91=(a45*a91);
  a11=(a59*a11);
  a93=(a61*a93);
  a11=(a11+a93);
  a93=(a62*a97);
  a96=(a64*a101);
  a93=(a93+a96);
  a11=(a11+a93);
  a11=(a26*a11);
  a91=(a91-a11);
  a91=(a1*a91);
  a91=(a26*a91);
  a11=(a111*a4);
  a93=(a115*a10);
  a11=(a11+a93);
  a93=(a116*a9);
  a11=(a11+a93);
  a91=(a91-a11);
  a91=(a91*a3);
  a11=(a5*a95);
  a16=(a16*a11);
  a93=(a5*a117);
  a21=(a21*a93);
  a16=(a16+a21);
  a21=(a5*a22);
  a96=(a23*a21);
  a36=(a5*a122);
  a0=(a29*a36);
  a96=(a96+a0);
  a16=(a16+a96);
  a16=(a26*a16);
  a96=(a5*a98);
  a15=(a15*a96);
  a0=(a5*a124);
  a20=(a20*a0);
  a15=(a15+a20);
  a20=(a5*a125);
  a76=(a18*a20);
  a49=(a5*a13);
  a88=(a28*a49);
  a76=(a76+a88);
  a15=(a15+a76);
  a15=(a45*a15);
  a16=(a16-a15);
  a16=(a1*a16);
  a16=(a26*a16);
  a65=(a65*a95);
  a35=(a35*a96);
  a65=(a65-a35);
  a41=(a41*a11);
  a59=(a59*a98);
  a41=(a41-a59);
  a65=(a65+a41);
  a37=(a37*a0);
  a67=(a67*a117);
  a37=(a37-a67);
  a61=(a61*a124);
  a43=(a43*a93);
  a61=(a61-a43);
  a37=(a37+a61);
  a65=(a65-a37);
  a37=(a68*a22);
  a61=(a38*a20);
  a37=(a37-a61);
  a61=(a44*a21);
  a43=(a62*a125);
  a61=(a61-a43);
  a37=(a37+a61);
  a61=(a40*a49);
  a43=(a70*a122);
  a61=(a61-a43);
  a43=(a64*a13);
  a93=(a46*a36);
  a43=(a43-a93);
  a61=(a61+a43);
  a37=(a37-a61);
  a65=(a65+a37);
  a65=(a45*a65);
  a65=(a1*a65);
  a65=(a45*a65);
  a16=(a16+a65);
  a21=(a52*a21);
  a36=(a54*a36);
  a21=(a21+a36);
  a21=(a55*a21);
  a20=(a48*a20);
  a49=(a50*a49);
  a20=(a20+a49);
  a20=(a45*a20);
  a21=(a21-a20);
  a21=(a1*a21);
  a21=(a55*a21);
  a16=(a16+a21);
  a95=(a5*a95);
  a95=(a56*a95);
  a21=(a5*a22);
  a21=(a56*a21);
  a95=(a95+a21);
  a16=(a16+a95);
  a95=(a111*a14);
  a21=(a115*a103);
  a95=(a95+a21);
  a21=(a116*a109);
  a95=(a95+a21);
  a16=(a16-a95);
  a16=(a16*a34);
  a91=(a91+a16);
  a68=(a68*a17);
  a70=(a70*a19);
  a68=(a68+a70);
  a68=(a45*a68);
  a62=(a62*a30);
  a64=(a64*a2);
  a62=(a62+a64);
  a62=(a55*a62);
  a68=(a68-a62);
  a68=(a1*a68);
  a68=(a55*a68);
  a62=(a111*a99);
  a64=(a115*a110);
  a62=(a62+a64);
  a64=(a116*a105);
  a62=(a62+a64);
  a68=(a68-a62);
  a68=(a68*a47);
  a91=(a91+a68);
  a57=(a57-a91);
  a91=(a111*a8);
  a68=(a115*a60);
  a91=(a91+a68);
  a68=(a116*a78);
  a91=(a91+a68);
  a91=(a91*a26);
  a68=(a111*a42);
  a62=(a115*a66);
  a68=(a68+a62);
  a62=(a116*a85);
  a68=(a68+a62);
  a68=(a68*a45);
  a91=(a91+a68);
  a111=(a111*a53);
  a115=(a115*a75);
  a111=(a111+a115);
  a116=(a116*a82);
  a111=(a111+a116);
  a111=(a111*a55);
  a91=(a91+a111);
  a57=(a57-a91);
  if (res[0]!=0) res[0][4]=a57;
  a33=(a120*a33);
  a69=(a121*a69);
  a33=(a33+a69);
  a84=(a92*a84);
  a33=(a33+a84);
  a6=(a81*a6);
  a104=(a83*a104);
  a6=(a6+a104);
  a6=(a55*a6);
  a97=(a77*a97);
  a101=(a79*a101);
  a97=(a97+a101);
  a97=(a26*a97);
  a6=(a6-a97);
  a6=(a1*a6);
  a6=(a26*a6);
  a4=(a120*a4);
  a10=(a121*a10);
  a4=(a4+a10);
  a9=(a92*a9);
  a4=(a4+a9);
  a6=(a6-a4);
  a6=(a6*a3);
  a22=(a81*a22);
  a122=(a83*a122);
  a22=(a22+a122);
  a22=(a55*a22);
  a125=(a77*a125);
  a13=(a79*a13);
  a125=(a125+a13);
  a125=(a45*a125);
  a22=(a22-a125);
  a22=(a1*a22);
  a22=(a45*a22);
  a14=(a120*a14);
  a103=(a121*a103);
  a14=(a14+a103);
  a109=(a92*a109);
  a14=(a14+a109);
  a22=(a22-a14);
  a22=(a22*a34);
  a6=(a6+a22);
  a22=(a5*a17);
  a23=(a23*a22);
  a34=(a5*a19);
  a29=(a29*a34);
  a23=(a23+a29);
  a23=(a26*a23);
  a29=(a5*a30);
  a18=(a18*a29);
  a14=(a5*a2);
  a28=(a28*a14);
  a18=(a18+a28);
  a18=(a55*a18);
  a23=(a23-a18);
  a23=(a1*a23);
  a23=(a26*a23);
  a44=(a44*a22);
  a46=(a46*a34);
  a44=(a44+a46);
  a44=(a45*a44);
  a38=(a38*a29);
  a40=(a40*a14);
  a38=(a38+a40);
  a38=(a55*a38);
  a44=(a44-a38);
  a44=(a1*a44);
  a44=(a45*a44);
  a23=(a23+a44);
  a81=(a81*a17);
  a48=(a48*a29);
  a81=(a81-a48);
  a52=(a52*a22);
  a77=(a77*a30);
  a52=(a52-a77);
  a81=(a81+a52);
  a50=(a50*a14);
  a83=(a83*a19);
  a50=(a50-a83);
  a79=(a79*a2);
  a54=(a54*a34);
  a79=(a79-a54);
  a50=(a50+a79);
  a81=(a81-a50);
  a81=(a55*a81);
  a1=(a1*a81);
  a1=(a55*a1);
  a23=(a23+a1);
  a5=(a5*a17);
  a56=(a56*a5);
  a23=(a23+a56);
  a99=(a120*a99);
  a110=(a121*a110);
  a99=(a99+a110);
  a105=(a92*a105);
  a99=(a99+a105);
  a23=(a23-a99);
  a23=(a23*a47);
  a6=(a6+a23);
  a33=(a33-a6);
  a8=(a120*a8);
  a60=(a121*a60);
  a8=(a8+a60);
  a78=(a92*a78);
  a8=(a8+a78);
  a8=(a8*a26);
  a42=(a120*a42);
  a66=(a121*a66);
  a42=(a42+a66);
  a85=(a92*a85);
  a42=(a42+a85);
  a42=(a42*a45);
  a8=(a8+a42);
  a120=(a120*a53);
  a121=(a121*a75);
  a120=(a120+a121);
  a92=(a92*a82);
  a120=(a120+a92);
  a120=(a120*a55);
  a8=(a8+a120);
  a33=(a33-a8);
  if (res[0]!=0) res[0][5]=a33;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_c(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_linearization_c_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_linearization_c_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_c_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_linearization_c_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_linearization_c_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_linearization_c_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_linearization_c_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_c_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int g_linearization_c_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_linearization_c_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_c_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    case 2: return "u";
    case 3: return "iH";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_linearization_c_name_out(casadi_int i){
  switch (i) {
    case 0: return "c";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_c_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_linearization_c_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_linearization_c_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
