/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_dynamics_generalized_coordinates_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* g_dynamics_H:(q[12])->(H[12x12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a0;
  if (res[0]!=0) res[0][68]=a0;
  if (res[0]!=0) res[0][69]=a0;
  if (res[0]!=0) res[0][70]=a0;
  if (res[0]!=0) res[0][71]=a0;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  if (res[0]!=0) res[0][76]=a0;
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a0;
  if (res[0]!=0) res[0][81]=a0;
  if (res[0]!=0) res[0][82]=a0;
  if (res[0]!=0) res[0][83]=a0;
  if (res[0]!=0) res[0][84]=a0;
  if (res[0]!=0) res[0][85]=a0;
  if (res[0]!=0) res[0][86]=a0;
  if (res[0]!=0) res[0][87]=a0;
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a0;
  if (res[0]!=0) res[0][90]=a0;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a0;
  if (res[0]!=0) res[0][93]=a0;
  if (res[0]!=0) res[0][94]=a0;
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a0;
  if (res[0]!=0) res[0][97]=a0;
  if (res[0]!=0) res[0][98]=a0;
  if (res[0]!=0) res[0][99]=a0;
  if (res[0]!=0) res[0][100]=a0;
  if (res[0]!=0) res[0][101]=a0;
  if (res[0]!=0) res[0][102]=a0;
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a0;
  if (res[0]!=0) res[0][107]=a0;
  if (res[0]!=0) res[0][108]=a0;
  if (res[0]!=0) res[0][109]=a0;
  if (res[0]!=0) res[0][110]=a0;
  if (res[0]!=0) res[0][111]=a0;
  if (res[0]!=0) res[0][112]=a0;
  if (res[0]!=0) res[0][113]=a0;
  if (res[0]!=0) res[0][114]=a0;
  if (res[0]!=0) res[0][115]=a0;
  if (res[0]!=0) res[0][116]=a0;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a0;
  if (res[0]!=0) res[0][119]=a0;
  if (res[0]!=0) res[0][120]=a0;
  if (res[0]!=0) res[0][121]=a0;
  if (res[0]!=0) res[0][122]=a0;
  if (res[0]!=0) res[0][123]=a0;
  if (res[0]!=0) res[0][124]=a0;
  if (res[0]!=0) res[0][125]=a0;
  if (res[0]!=0) res[0][126]=a0;
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a0;
  if (res[0]!=0) res[0][129]=a0;
  if (res[0]!=0) res[0][130]=a0;
  if (res[0]!=0) res[0][131]=a0;
  if (res[0]!=0) res[0][132]=a0;
  if (res[0]!=0) res[0][133]=a0;
  if (res[0]!=0) res[0][134]=a0;
  if (res[0]!=0) res[0][135]=a0;
  if (res[0]!=0) res[0][136]=a0;
  if (res[0]!=0) res[0][137]=a0;
  if (res[0]!=0) res[0][138]=a0;
  if (res[0]!=0) res[0][139]=a0;
  if (res[0]!=0) res[0][140]=a0;
  if (res[0]!=0) res[0][141]=a0;
  if (res[0]!=0) res[0][142]=a0;
  if (res[0]!=0) res[0][143]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_H(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_dynamics_H_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_H_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_H_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_dynamics_H_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_H_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_H_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_H_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_H_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_H_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_dynamics_H_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_H_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_H_name_out(casadi_int i){
  switch (i) {
    case 0: return "H";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_H_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_H_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_dynamics_H_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_dynamics_c:(q[12],v[12])->(c[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[1]? arg[1][0] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a0=(-a0);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_c(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_dynamics_c_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_c_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_c_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_dynamics_c_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_c_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_c_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_c_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_c_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_c_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_dynamics_c_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_c_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_c_name_out(casadi_int i){
  switch (i) {
    case 0: return "c";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_c_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_c_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_dynamics_c_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_dynamics_T:(q[12])->(T[12x12]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a1;
  if (res[0]!=0) res[0][38]=a1;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a1;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a1;
  if (res[0]!=0) res[0][43]=a1;
  if (res[0]!=0) res[0][44]=a1;
  if (res[0]!=0) res[0][45]=a1;
  if (res[0]!=0) res[0][46]=a1;
  if (res[0]!=0) res[0][47]=a1;
  if (res[0]!=0) res[0][48]=a1;
  if (res[0]!=0) res[0][49]=a1;
  if (res[0]!=0) res[0][50]=a1;
  if (res[0]!=0) res[0][51]=a1;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a1;
  if (res[0]!=0) res[0][54]=a1;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a1;
  if (res[0]!=0) res[0][57]=a1;
  if (res[0]!=0) res[0][58]=a1;
  if (res[0]!=0) res[0][59]=a1;
  if (res[0]!=0) res[0][60]=a1;
  if (res[0]!=0) res[0][61]=a1;
  if (res[0]!=0) res[0][62]=a1;
  if (res[0]!=0) res[0][63]=a1;
  if (res[0]!=0) res[0][64]=a1;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a1;
  if (res[0]!=0) res[0][67]=a1;
  if (res[0]!=0) res[0][68]=a1;
  if (res[0]!=0) res[0][69]=a1;
  if (res[0]!=0) res[0][70]=a1;
  if (res[0]!=0) res[0][71]=a1;
  if (res[0]!=0) res[0][72]=a1;
  if (res[0]!=0) res[0][73]=a1;
  if (res[0]!=0) res[0][74]=a1;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a1;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a1;
  if (res[0]!=0) res[0][80]=a1;
  if (res[0]!=0) res[0][81]=a1;
  if (res[0]!=0) res[0][82]=a1;
  if (res[0]!=0) res[0][83]=a1;
  if (res[0]!=0) res[0][84]=a1;
  if (res[0]!=0) res[0][85]=a1;
  if (res[0]!=0) res[0][86]=a1;
  if (res[0]!=0) res[0][87]=a1;
  if (res[0]!=0) res[0][88]=a1;
  if (res[0]!=0) res[0][89]=a1;
  if (res[0]!=0) res[0][90]=a1;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a1;
  if (res[0]!=0) res[0][93]=a1;
  if (res[0]!=0) res[0][94]=a1;
  if (res[0]!=0) res[0][95]=a1;
  if (res[0]!=0) res[0][96]=a1;
  if (res[0]!=0) res[0][97]=a1;
  if (res[0]!=0) res[0][98]=a1;
  if (res[0]!=0) res[0][99]=a1;
  if (res[0]!=0) res[0][100]=a1;
  if (res[0]!=0) res[0][101]=a1;
  if (res[0]!=0) res[0][102]=a1;
  if (res[0]!=0) res[0][103]=a1;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a1;
  if (res[0]!=0) res[0][106]=a1;
  if (res[0]!=0) res[0][107]=a1;
  if (res[0]!=0) res[0][108]=a1;
  if (res[0]!=0) res[0][109]=a1;
  if (res[0]!=0) res[0][110]=a1;
  if (res[0]!=0) res[0][111]=a1;
  if (res[0]!=0) res[0][112]=a1;
  if (res[0]!=0) res[0][113]=a1;
  if (res[0]!=0) res[0][114]=a1;
  if (res[0]!=0) res[0][115]=a1;
  if (res[0]!=0) res[0][116]=a1;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a1;
  if (res[0]!=0) res[0][119]=a1;
  if (res[0]!=0) res[0][120]=a1;
  if (res[0]!=0) res[0][121]=a1;
  if (res[0]!=0) res[0][122]=a1;
  if (res[0]!=0) res[0][123]=a1;
  if (res[0]!=0) res[0][124]=a1;
  if (res[0]!=0) res[0][125]=a1;
  if (res[0]!=0) res[0][126]=a1;
  if (res[0]!=0) res[0][127]=a1;
  if (res[0]!=0) res[0][128]=a1;
  if (res[0]!=0) res[0][129]=a1;
  if (res[0]!=0) res[0][130]=a0;
  if (res[0]!=0) res[0][131]=a1;
  if (res[0]!=0) res[0][132]=a1;
  if (res[0]!=0) res[0][133]=a1;
  if (res[0]!=0) res[0][134]=a1;
  if (res[0]!=0) res[0][135]=a1;
  if (res[0]!=0) res[0][136]=a1;
  if (res[0]!=0) res[0][137]=a1;
  if (res[0]!=0) res[0][138]=a1;
  if (res[0]!=0) res[0][139]=a1;
  if (res[0]!=0) res[0][140]=a1;
  if (res[0]!=0) res[0][141]=a1;
  if (res[0]!=0) res[0][142]=a1;
  if (res[0]!=0) res[0][143]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_T(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_dynamics_T_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_dynamics_T_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_T_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_dynamics_T_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_dynamics_T_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_T_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_dynamics_T_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_T_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_dynamics_T_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_dynamics_T_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_T_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_dynamics_T_name_out(casadi_int i){
  switch (i) {
    case 0: return "T";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_T_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_dynamics_T_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_dynamics_T_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
