function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Oct-2020 21:10:31

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = -q2;
t3 = -q3;
t4 = q1+t2;
t5 = q1+t3;
t6 = q2+t3;
t7 = cos(t4);
t8 = cos(t5);
t9 = cos(t6);
t10 = t8.*(1.8e+1./5.0);
t11 = t9.*(1.8e+1./5.0);
t12 = t7.*(5.4e+1./5.0);
H = reshape([8.6e+1./5.0,t12,t10,t12,1.0e+1,t11,t10,t11,1.4e+1./5.0],[3,3]);
