function c = g_dynamics_c(in1,in2)
%G_DYNAMICS_C
%    C = G_DYNAMICS_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Oct-2020 21:10:31

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = -q2;
t3 = -q3;
t4 = -v2;
t5 = -v3;
t6 = q1+t2;
t7 = q1+t3;
t8 = q2+t3;
t9 = t4+v1;
t10 = t5+v1;
t11 = t5+v2;
t12 = sin(t6);
t13 = sin(t7);
t14 = sin(t8);
c = [-v1+sin(q1).*2.94e+2-t9.*t12.*v2.*(2.7e+1./5.0)-t10.*t13.*v3.*(9.0./5.0);t4+sin(q2).*(8.82e+2./5.0)-t9.*t12.*v1.*(2.7e+1./5.0)-t11.*t14.*v3.*(9.0./5.0);t5+sin(q3).*(2.94e+2./5.0)-t10.*t13.*v1.*(9.0./5.0)-t11.*t14.*v2.*(9.0./5.0)];
