function H = g_dynamics_H(in1)
%G_DYNAMICS_H
%    H = G_DYNAMICS_H(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Dec-2020 12:43:20

q2 = in1(2,:);
q3 = in1(3,:);
t2 = q2+q3;
t3 = cos(t2);
t4 = cos(q2);
t5 = cos(q3);
t6 = t5.*(5.0./2.0);
t7 = t3.*(5.0./4.0);
t8 = t4.*(1.5e1./4.0);
t9 = t6+t7+t8+5.5e1./1.2e1;
t10 = t5.*(5.0./4.0);
t11 = t7+t10+2.5e1./2.4e1;
t12 = t10+2.5e1./2.4e1;
H = reshape([t3.*(5.0./2.0)+t4.*(1.5e1./2.0)+t6+8.5e1./8.0,t9,t11,t9,t6+5.5e1./1.2e1,t12,t11,t12,2.5e1./2.4e1],[3,3]);
