function T = g_dynamics_T(in1)
%G_DYNAMICS_T
%    T = G_DYNAMICS_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Mar-2021 22:10:43

T = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
