function TaskJacobian_derivative = g_InverseKinematics_TaskJacobian_derivative(in1,in2)
%G_INVERSEKINEMATICS_TASKJACOBIAN_DERIVATIVE
%    TASKJACOBIAN_DERIVATIVE = G_INVERSEKINEMATICS_TASKJACOBIAN_DERIVATIVE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 16:34:02

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
v1 = in2(1,:);
v2 = in2(2,:);
v3 = in2(3,:);
t2 = sin(q1);
t3 = sin(q2);
t4 = sin(q3);
TaskJacobian_derivative = reshape([t2.*v1.*(-1.0./2.0),v1.*cos(q1).*(-1.0./2.0),t2.*v1.*(-3.0./5.0),t3.*v2.*(-3.0./1.0e+1),v2.*cos(q2).*(-3.0./1.0e+1),t3.*v2.*(-3.0./5.0),t4.*v3.*(-1.0./1.0e+1),v3.*cos(q3).*(-1.0./1.0e+1),t4.*v3.*(-3.0./5.0)],[3,3]);
