function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Nov-2020 19:17:26

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
Task = [q1;q2;cos(q1+q2+q3).*(1.0./2.0)+cos(q1+q2).*(1.0./2.0)+cos(q1).*(1.0./2.0)];
