function TaskJacobian = g_InverseKinematics_TaskJacobian(in1)
%G_INVERSEKINEMATICS_TASKJACOBIAN
%    TASKJACOBIAN = G_INVERSEKINEMATICS_TASKJACOBIAN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Sep-2020 16:34:02

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
TaskJacobian = reshape([t2./2.0,sin(q1).*(-1.0./2.0),t2.*(3.0./5.0),t3.*(3.0./1.0e+1),sin(q2).*(-3.0./1.0e+1),t3.*(3.0./5.0),t4./1.0e+1,sin(q3).*(-1.0./1.0e+1),t4.*(3.0./5.0)],[3,3]);
