function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Dec-2020 12:44:56

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
t3 = q1+q2;
t4 = sin(t2);
t5 = sin(t3);
t6 = sin(q1);
t7 = cos(t2);
t8 = cos(t3);
t9 = cos(q1);
Task = [0.0;t4.*(-1.0./1.2e1)-t5.*(1.0./4.0)-t6.*(5.0./1.2e1);t7.*(1.0./1.2e1)+t8.*(1.0./4.0)+t9.*(5.0./1.2e1);0.0;t4.*(-1.0./2.0)-t5.*(1.0./2.0)-t6.*(1.0./2.0);t7.*(1.0./2.0)+t8.*(1.0./2.0)+t9.*(1.0./2.0)];
